import {createSessionStore,sessionKey} from './session-store.js';
import {taskToolsMarkup,mountTaskTools,validateFile} from './task-tools.js';
import {mountOwnerSpace} from './owner-space.js';
import {taskMetrics,escapeHtml as h} from './metrics.js';
const $=s=>document.querySelector(s),labels={backlog:'Черга',todo:'До виконання',progress:'У роботі',blocked:'Заблоковано',review:'На перевірці',ready:'Готово до запуску',done:'Завершено'};
let config,session,actor,tasks=[],assignees=[],team=[],view='control',selected,busy=false,authEpoch=0;
const sessions=createSessionStore({persistent:localStorage,temporary:sessionStorage,refresh:refresh_token=>request('/auth/v1/token?grant_type=refresh_token',{refresh_token}),lock:fn=>navigator.locks?navigator.locks.request('cmo-session-refresh',fn):fn(),onEnd:lockWorkspace});
session=sessions.read();
function notice(message=''){$('#notice').textContent=message;}
function storeSession(s,remember){authEpoch++;sessions.save(s,remember);session=sessions.read();}
function lockWorkspace(){authEpoch++;session=null;actor=null;selected=null;tasks=[];team=[];assignees=[];ownerSpace.setActor(null);ownerSpace.hide();$('#owner-space').replaceChildren();$('#workspace').hidden=true;$('#login').hidden=false;$('#identity').textContent='';$('#heading').textContent='Увійти в Workspace';$('#sync').textContent='Потрібен вхід';for(const id of ['#reload','#logout','#new-task'])$(id).hidden=true;for(const id of ['#board','#stats','#access-summary','#task-detail'])$(id).replaceChildren();document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.querySelectorAll('nav button').forEach(b=>b.disabled=true);}
async function request(path,body,token){const res=await fetch(config.url+path,{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const data=await res.json();if(!res.ok){const e=Error(data.msg||data.error_description||data.message||'Не вдалося виконати дію');e.status=res.status;throw e;}return data;}
async function token(){const access=await sessions.token();session=sessions.read();return access;}
async function rpc(body,endpoint='cmo_workspace'){const access=await token();const res=await fetch(config.url+'/rest/v1/rpc/'+endpoint,{method:'POST',headers:{apikey:config.key,Authorization:`Bearer ${access}`,'Content-Type':'application/json','Content-Profile':'api','Accept-Profile':'api'},body:JSON.stringify({body})});const data=await res.json();if(!res.ok)throw Error(data.message||'Не вдалося зберегти. Спробуй оновити задачник.');return data;}
const ownerSpace=mountOwnerSpace({request:body=>rpc(body,'cmo_owner_data'),backupStatus:()=>rpc({},'cmo_backup_status'),notice,getTasks:()=>tasks,getTeam:()=>team,openTask:showTask,openAssignee});
function dates(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('uk-UA',{timeZone:'Europe/Kyiv',dateStyle:'short',timeStyle:'short'}).format(d);}
function options(selectedValue=''){return assignees.map(n=>`<option ${n===selectedValue?'selected':''}>${h(n)}</option>`).join('');}
async function load(){const epoch=authEpoch;notice();$('#sync').textContent='Оновлення…';try{const data=await rpc({op:'list'});if(epoch!==authEpoch||!sessions.read())return;actor=data.actor;ownerSpace.setActor(actor);if(actor.role!=='owner'&&view==='control')view='mine';tasks=data.tasks;assignees=data.assignees;team=data.team||[];document.querySelectorAll('nav button[data-view]').forEach(b=>b.disabled=false);$('#login').hidden=true;$('#workspace').hidden=false;$('#reload').hidden=false;$('#logout').hidden=false;$('#identity').textContent=actor.name+' · '+({owner:'Керівник',intake:'Створення задач',executor:'Виконавець'}[actor.role]);$('#new-task').hidden=!['owner','intake'].includes(actor.role);$('#assignee-filter').innerHTML='<option value="">Усі доступні</option>'+options();$('#create-form [name=assignee]').innerHTML=options(actor.name);$('#sync').textContent='Дані отримано '+dates(new Date().toISOString());renderAccess();render();}catch(error){$('#sync').textContent='Помилка підключення';notice(error.message);if(!actor){$('#login').hidden=false;$('#workspace').hidden=true;}}}
function renderAccess(){const owner=actor.role==='owner',intake=actor.role==='intake';$('#access-summary').innerHTML=`<details><summary>Мій доступ · ${owner?'Керівник':intake?'Постановник задач':'Виконавець'}</summary><p>${owner?'Усі задачі, команда, плани, бюджети, аналітика та резервні копії. Ти повертаєш роботу з рев’ю й приймаєш результат.':intake?'Свої задачі, створені тобою та передані тобою далі. Можеш створювати задачі для активних учасників команди.':'Свої задачі та ті, які ти передав далі. Чужі задачі поза цією участю недоступні.'}</p>${owner?'':`<p>У власних задачах: робота, чеклист, результат, блокування й передача. Після здачі на рев’ю або передачі іншому: перегляд і коментарі. Остаточно приймає результат керівник.</p><p>Бюджети, загальна аналітика, стратегія, управління доступами та резервні копії доступні керівнику.</p>`}</details>`;document.querySelector('[data-view=control]').textContent=owner?'Контроль':'Мій контроль';document.querySelector('[data-view=board]').textContent=owner?'Задачник':'Доступні задачі';}
function openAssignee(name){view='board';$('#assignee-filter').value=name;$('#search').value='';$('#hide-done').checked=true;render();}
function render(){
 if(!actor)return;
 ownerSpace.hide();$('#workspace').hidden=false;$('#new-task').hidden=!['owner','intake'].includes(actor.role);
 document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 const base=tasks.filter(t=>view!=='mine'||t.assignee===actor.name),m=taskMetrics(base);
 $('#stats').innerHTML=[['Відкриті',m.open],['На перевірці',m.review],['Заблоковані',m.blocked],['Прострочені',m.overdue]].map(([label,n])=>`<div class="stat"><strong>${n}</strong><span>${label}</span></div>`).join('');
 const term=$('#search').value.toLocaleLowerCase('uk'),lanes=view==='control'?['blocked','review','progress','todo','ready','backlog']:Object.keys(labels);
 const filtered=base.filter(t=>lanes.includes(t.lane)&&(!$('#hide-done').checked||t.lane!=='done')&&(!$('#assignee-filter').value||t.assignee===$('#assignee-filter').value)&&(t.title+' '+t.description+' '+t.assignee).toLocaleLowerCase('uk').includes(term));
 $('#board-summary').textContent=`Показано ${filtered.length} · Усього доступно ${base.length}`;
 $('#board').innerHTML=lanes.map(l=>{const rows=filtered.filter(t=>t.lane===l);return `<section class="column" data-lane="${l}"><h3><span class="lane-dot"></span>${labels[l]} <span class="lane-count">${rows.length}</span></h3>${rows.map(t=>{const checks=t.checklist||[],done=checks.filter(c=>c.done).length;return `<button class="card" data-task="${h(t.id)}"><small>${h(t.id.replace('task-','PV-'))} <span class="pill ${h(t.priority)}">${h(t.priority)}</span></small><strong>${h(t.title)}</strong>${checks.length?`<div class="task-progress" aria-label="Чеклист: ${done} з ${checks.length}"><progress value="${done}" max="${checks.length}"></progress><span>${done}/${checks.length}</span></div>`:''}<footer><span class="assignee-name">${h(t.assignee)}</span><span>${h(t.due)}</span></footer></button>`}).join('')||'<p class="empty">Немає задач</p>'}</section>`}).join('');
 $('#heading').textContent={control:actor.role==='owner'?'Робота під контролем':'Мій контроль',board:actor.role==='owner'?'Командний задачник':'Доступні задачі',mine:'Мої задачі'}[view];
}
function showTask(id){selected=tasks.find(t=>t.id===id);if(!selected)return;$('#task-error').textContent='';const t=selected,canWork=t.permissions?.work===true,canEdit=t.permissions?.edit===true,canComment=t.permissions?.comment===true;$('#task-title').textContent=t.title;$('#task-detail').innerHTML=`<div class="metadata"><span>${h(t.assignee)}</span><span>${h(labels[t.lane])}</span><span>${h(t.priority)}</span><span>${h(t.due)}</span></div><p class="description">${h(t.description)}</p>${t.result?`<h3>Результат / блокування</h3><p class="description">${h(t.result)}</p>`:''}${taskToolsMarkup(t,tasks,assignees,actor)}${canWork?`<div class="operations"><button data-move="progress">Прийняти в роботу</button><button data-move="review">На перевірку</button><button data-move="blocked">Заблокувати</button>${actor.role==='owner'?'<button data-move="todo">Повернути до роботи</button><button data-move="ready">Готово до запуску</button><button data-move="done">Прийняти результат</button>':''}</div><label>Результат або причина блокування<textarea id="result" rows="3">${h(t.result||'')}</textarea></label><div class="operation"><h3>Передати задачу</h3><select id="handoff-to" aria-label="Передати кому">${options(t.assignee)}</select><label>Що потрібно зробити далі<textarea id="handoff-text" rows="2"></textarea></label><button id="handoff">Передати</button></div>`:''}${canComment?`<div class="operation"><label>Коментар<textarea id="comment" rows="2"></textarea></label><button id="send-comment">Додати коментар</button></div>`:''}${!canWork&&canComment?'<p class="access-note">Доступні перегляд і коментарі. Задачу на рев’ю повертає до роботи керівник.</p>':''}${canEdit?`<details><summary>Редагувати умови</summary><form id="edit-form"><label>Назва<input name="title" value="${h(t.title)}" maxlength="500" required></label><label>Опис<textarea name="description" rows="5" maxlength="20000">${h(t.description)}</textarea></label><label>Пріоритет<select name="priority">${['High','Medium','Low'].map(p=>`<option ${t.priority===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Дедлайн<input name="due" value="${h(t.due)}"></label><button>Зберегти умови</button></form></details>`:''}<h3>Коментарі</h3>${t.comments.map(c=>`<div class="comment"><strong>${h(c.author||c.actor||'')}</strong> · ${h(dates(c.at))}<p>${h(c.text)}</p></div>`).join('')||'<p>Коментарів немає</p>'}<details><summary>Історія · ${t.activity.length}</summary>${t.activity.slice().reverse().map(a=>`<div class="event"><strong>${h(a.actor)}</strong> · ${h(a.action)}<p>${h(a.note)}</p><em>${h(dates(a.at))}</em></div>`).join('')}</details>`;if(!$('#task-dialog').open)$('#task-dialog').showModal();}
async function mutate(body){if(busy)return;busy=true;notice();const id=selected?.id;try{await rpc({...body,id,version:selected?.version});await load();if(tasks.some(t=>t.id===id))showTask(id);else{selected=null;$('#task-dialog').close();}}catch(error){notice(error.message);$('#task-error').textContent=error.message;}finally{busy=false;}}

async function uploadTaskFile(file){if(busy)return;busy=true;const task=selected;try{const mime=validateFile(file);notice('Завантаження файлу…');const prepared=await rpc({op:'attachment_prepare',id:task.id,version:task.version,name:file.name,size:file.size,mime});const f=prepared.attachment;const res=await fetch(config.url+'/storage/v1/object/cmo-task-files/'+f.path,{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+await token(),'Content-Type':mime,'x-upsert':'false'},body:file});if(!res.ok){const e=await res.json();throw Error(e.message||e.error||'Не вдалося завантажити файл');}await rpc({op:'attachment_confirm',id:task.id,version:prepared.version,attachmentId:f.id});await load();showTask(task.id);notice('Файл додано');}catch(e){await load();showTask(task.id);notice(e.message);$('#task-error').textContent=e.message+' Якщо файл уже завантажився, натисни «Перевірити завантаження».';}finally{busy=false;}}
async function downloadTaskFile(f){try{const res=await fetch(config.url+'/storage/v1/object/authenticated/cmo-task-files/'+f.path,{headers:{apikey:config.key,Authorization:'Bearer '+await token()}});if(!res.ok)throw Error('Файл недоступний або доступ змінився');const url=URL.createObjectURL(await res.blob()),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){notice(e.message);}}
mountTaskTools($('#task-detail'),{getTask:()=>selected,getTasks:()=>tasks,mutate,openTask:showTask,upload:uploadTaskFile,download:downloadTaskFile,notice});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{storeSession(await request('/auth/v1/token?grant_type=password',{email:f.get('email'),password:f.get('password')}),f.get('remember')==='on');e.target.reset();await load();}catch(error){notice(error.message);}});
$('#signup').addEventListener('click',async()=>{const form=$('#login-form');if(!form.reportValidity())return;const f=new FormData(form);try{await request('/auth/v1/signup',{email:f.get('email'),password:f.get('password')});form.querySelector('[name=password]').value='';notice('Перевір пошту та підтвердь обліковий запис. Після цього увійди.');}catch(error){notice(error.message);}});
$('#logout').addEventListener('click',async()=>{const access=sessions.read()?.access_token;sessions.clear();try{if(access)await request('/auth/v1/logout?scope=local',{},access);}catch{}notice('Ти вийшов із Workspace.');});
window.addEventListener('storage',e=>{if(e.key!==sessionKey)return;authEpoch++;session=sessions.read();if(!session)lockWorkspace();else if(config)load();});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&sessions.read()&&config)token().catch(e=>notice(e.message));});
$('#reload').addEventListener('click',load);document.querySelectorAll('nav button[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render();}));['#search','#assignee-filter','#hide-done'].forEach(s=>$(s).addEventListener('input',render));$('#board').addEventListener('click',e=>{const b=e.target.closest('[data-task]');if(b)showTask(b.dataset.task);});$('#close-dialog').addEventListener('click',()=>$('#task-dialog').close());$('#close-create').addEventListener('click',()=>$('#create-dialog').close());$('#new-task').addEventListener('click',()=>{$('#create-error').textContent='';$('#create-dialog').showModal();});
$('#create-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;try{await rpc({op:'create',...Object.fromEntries(new FormData(e.target))});$('#create-dialog').close();e.target.reset();await load();}catch(error){notice(error.message);$('#create-error').textContent=error.message;}finally{busy=false;}});
$('#task-detail').addEventListener('change',e=>{if(e.target.matches('[data-check]'))mutate({op:'check',index:Number(e.target.dataset.check),done:e.target.checked});});$('#task-detail').addEventListener('submit',e=>{if(e.target.id==='edit-form'){e.preventDefault();mutate({op:'edit',...Object.fromEntries(new FormData(e.target))});}});$('#task-detail').addEventListener('click',e=>{const move=e.target.closest('[data-move]');if(move)mutate({op:'move',lane:move.dataset.move,result:$('#result').value});if(e.target.id==='handoff')mutate({op:'handoff',assignee:$('#handoff-to').value,text:$('#handoff-text').value});if(e.target.id==='send-comment')mutate({op:'comment',text:$('#comment').value});});
document.querySelectorAll('nav button[data-view]').forEach(b=>b.disabled=!actor);
try{config=await (await fetch('/api/config')).json();if(!config.url||!config.key)throw Error('Workspace ще не підключений. Потрібні налаштування сервера.');if(session)await load();else{$('#login').hidden=false;$('#sync').textContent='Потрібен вхід';}}catch(error){notice(error.message);$('#sync').textContent='Очікує налаштування';}
