import {taskMetrics,escapeHtml as h} from './metrics.js';
const $=s=>document.querySelector(s),labels={backlog:'Черга',todo:'До виконання',progress:'У роботі',blocked:'Заблоковано',review:'На перевірці',ready:'Готово до запуску',done:'Завершено'};
let config,session,actor,tasks=[],assignees=[],view='control',selected,busy=false;
try{session=JSON.parse(sessionStorage.getItem('cmo-session')||'null');}catch{session=null;}
function notice(message=''){$('#notice').textContent=message;}
function storeSession(s){session=s;if(s){s.expires_at??=Math.floor(Date.now()/1000)+(s.expires_in||3600);sessionStorage.setItem('cmo-session',JSON.stringify(s));}else sessionStorage.removeItem('cmo-session');}
async function request(path,body,token){const res=await fetch(config.url+path,{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.msg||data.error_description||data.message||'Не вдалося виконати дію');return data;}
async function token(){if(!session)throw Error('Увійди в Workspace');if(session.expires_at*1000<Date.now()+60000){try{storeSession(await request('/auth/v1/token?grant_type=refresh_token',{refresh_token:session.refresh_token}));}catch(error){storeSession(null);throw error;}}return session.access_token;}
async function rpc(body){const access=await token();const res=await fetch(config.url+'/rest/v1/rpc/cmo_workspace',{method:'POST',headers:{apikey:config.key,Authorization:`Bearer ${access}`,'Content-Type':'application/json','Content-Profile':'api','Accept-Profile':'api'},body:JSON.stringify({body})});const data=await res.json();if(!res.ok)throw Error(data.message||'Не вдалося зберегти. Спробуй оновити задачник.');return data;}
function dates(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('uk-UA',{timeZone:'Europe/Kyiv',dateStyle:'short',timeStyle:'short'}).format(d);}
function options(selectedValue=''){return assignees.map(n=>`<option ${n===selectedValue?'selected':''}>${h(n)}</option>`).join('');}
async function load(){notice();$('#sync').textContent='Оновлення…';try{const data=await rpc({op:'list'});actor=data.actor;tasks=data.tasks;assignees=data.assignees;$('#login').hidden=true;$('#workspace').hidden=false;$('#reload').hidden=false;$('#logout').hidden=false;$('#identity').textContent=actor.name+' · '+({owner:'Керівник',intake:'Створення задач',executor:'Виконавець'}[actor.role]);$('#new-task').hidden=!['owner','intake'].includes(actor.role);$('#assignee-filter').innerHTML='<option value="">Усі доступні</option>'+options();$('#create-form [name=assignee]').innerHTML=options(actor.name);$('#sync').textContent='Дані отримано '+dates(new Date().toISOString());render();}catch(error){$('#sync').textContent='Помилка підключення';notice(error.message);if(!actor){$('#login').hidden=false;$('#workspace').hidden=true;}}}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const m=taskMetrics(tasks);$('#stats').innerHTML=[['Відкриті',m.open],['На перевірці',m.review],['Заблоковані',m.blocked],['Прострочені',m.overdue]].map(([label,n])=>`<div class="stat"><strong>${n}</strong><span>${label}</span></div>`).join('');const term=$('#search').value.toLocaleLowerCase('uk');const filtered=tasks.filter(t=>(view!=='mine'||t.assignee===actor.name)&&(!$('#hide-done').checked||t.lane!=='done')&&(!$('#assignee-filter').value||t.assignee===$('#assignee-filter').value)&&(t.title+' '+t.description).toLocaleLowerCase('uk').includes(term));const lanes=view==='control'?['blocked','review','progress','todo']:Object.keys(labels);$('#board').innerHTML=lanes.map(l=>{const rows=filtered.filter(t=>t.lane===l);return `<section class="column"><h3>${labels[l]} · ${rows.length}</h3>${rows.map(t=>`<button class="card" data-task="${h(t.id)}"><small>${h(t.id.replace('task-','PV-'))} <span class="pill ${h(t.priority)}">${h(t.priority)}</span></small><strong>${h(t.title)}</strong><footer><span>${h(t.assignee)}</span><span>${h(t.due)}</span></footer></button>`).join('')||'<p class="empty">Немає задач</p>'}</section>`}).join('');$('#heading').textContent={control:'Робота під контролем',board:'Командний задачник',mine:'Мої задачі'}[view];}
function showTask(id){selected=tasks.find(t=>t.id===id);if(!selected)return;const t=selected,canWork=actor.role==='owner'||t.assignee===actor.name,canEdit=canWork&&['owner','intake'].includes(actor.role);$('#task-title').textContent=t.title;$('#task-detail').innerHTML=`<div class="metadata"><span>${h(t.assignee)}</span><span>${h(labels[t.lane])}</span><span>${h(t.priority)}</span><span>${h(t.due)}</span></div><p class="description">${h(t.description)}</p>${t.result?`<h3>Результат / блокування</h3><p class="description">${h(t.result)}</p>`:''}<h3>Чеклист</h3>${t.checklist.map((c,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${c.done?'checked':''} ${canWork?'':'disabled'}>${h(c.text)}</label>`).join('')||'<p>Пунктів немає</p>'}${canWork?`<div class="operations"><button data-move="progress">Прийняти в роботу</button><button data-move="review">На перевірку</button><button data-move="blocked">Заблокувати</button>${actor.role==='owner'?'<button data-move="todo">Повернути до роботи</button><button data-move="ready">Готово до запуску</button><button data-move="done">Прийняти результат</button>':''}</div><label>Результат або причина блокування<textarea id="result" rows="3"></textarea></label><div class="operation"><h3>Передати задачу</h3><select id="handoff-to" aria-label="Передати кому">${options(t.assignee)}</select><label>Що потрібно зробити далі<textarea id="handoff-text" rows="2"></textarea></label><button id="handoff">Передати</button></div><div class="operation"><label>Коментар<textarea id="comment" rows="2"></textarea></label><button id="send-comment">Додати коментар</button></div>`:''}${canEdit?`<details><summary>Редагувати умови</summary><form id="edit-form"><label>Назва<input name="title" value="${h(t.title)}" maxlength="500" required></label><label>Опис<textarea name="description" rows="5" maxlength="20000">${h(t.description)}</textarea></label><label>Пріоритет<select name="priority">${['High','Medium','Low'].map(p=>`<option ${t.priority===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Дедлайн<input name="due" value="${h(t.due)}"></label><button>Зберегти умови</button></form></details>`:''}<h3>Коментарі</h3>${t.comments.map(c=>`<div class="comment"><strong>${h(c.author||c.actor||'')}</strong> · ${h(dates(c.at))}<p>${h(c.text)}</p></div>`).join('')||'<p>Коментарів немає</p>'}<details><summary>Історія · ${t.activity.length}</summary>${t.activity.slice().reverse().map(a=>`<div class="event"><strong>${h(a.actor)}</strong> · ${h(a.action)}<p>${h(a.note)}</p><em>${h(dates(a.at))}</em></div>`).join('')}</details>`;if(!$('#task-dialog').open)$('#task-dialog').showModal();}
async function mutate(body){if(busy)return;busy=true;notice();const id=selected?.id;try{await rpc({...body,id,version:selected?.version});await load();if(id)showTask(id);}catch(error){notice(error.message);$('#task-dialog').close();}finally{busy=false;}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{storeSession(await request('/auth/v1/token?grant_type=password',{email:f.get('email'),password:f.get('password')}));e.target.reset();await load();}catch(error){notice(error.message);}});
$('#signup').addEventListener('click',async()=>{const form=$('#login-form');if(!form.reportValidity())return;const f=new FormData(form);try{await request('/auth/v1/signup',{email:f.get('email'),password:f.get('password')});form.querySelector('[name=password]').value='';notice('Перевір пошту та підтвердь обліковий запис. Після цього увійди.');}catch(error){notice(error.message);}});
$('#logout').addEventListener('click',async()=>{try{await request('/auth/v1/logout',{},await token());}catch{}storeSession(null);location.reload();});
$('#reload').addEventListener('click',load);document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render();}));['#search','#assignee-filter','#hide-done'].forEach(s=>$(s).addEventListener('input',render));$('#board').addEventListener('click',e=>{const b=e.target.closest('[data-task]');if(b)showTask(b.dataset.task);});$('#close-dialog').addEventListener('click',()=>$('#task-dialog').close());$('#close-create').addEventListener('click',()=>$('#create-dialog').close());$('#new-task').addEventListener('click',()=>$('#create-dialog').showModal());
$('#create-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;try{await rpc({op:'create',...Object.fromEntries(new FormData(e.target))});$('#create-dialog').close();e.target.reset();await load();}catch(error){notice(error.message);$('#create-dialog').close();}finally{busy=false;}});
$('#task-detail').addEventListener('change',e=>{if(e.target.matches('[data-check]'))mutate({op:'check',index:Number(e.target.dataset.check),done:e.target.checked});});$('#task-detail').addEventListener('submit',e=>{if(e.target.id==='edit-form'){e.preventDefault();mutate({op:'edit',...Object.fromEntries(new FormData(e.target))});}});$('#task-detail').addEventListener('click',e=>{const move=e.target.closest('[data-move]');if(move)mutate({op:'move',lane:move.dataset.move,result:$('#result').value});if(e.target.id==='handoff')mutate({op:'handoff',assignee:$('#handoff-to').value,text:$('#handoff-text').value});if(e.target.id==='send-comment')mutate({op:'comment',text:$('#comment').value});});
try{config=await (await fetch('/api/config')).json();if(!config.url||!config.key)throw Error('Workspace ще не підключений. Потрібні налаштування сервера.');if(session)await load();else{$('#login').hidden=false;$('#sync').textContent='Потрібен вхід';}}catch(error){notice(error.message);$('#sync').textContent='Очікує налаштування';}
