import {escapeHtml as h} from './metrics.js';
import {creativeGroups,reviewLabels,previewKind} from './creative-model.js';
export function creativeMarkup(task,actor){const groups=creativeGroups(task),work=task.permissions?.work;
 return `<section class="task-section creative-section"><h3>Креативи та погодження</h3><p class="task-help">Погодження стосується конкретної версії. Нова версія проходить перевірку заново.</p>${groups.map(g=>`<article class="creative-group"><div><strong>${h(g.versions[0].name)}</strong><span class="creative-status status-${h(g.latest.review?.status||'pending')}">V${g.latest.assetVersion} · ${h(g.latest.status==='ready'?reviewLabels[g.latest.review?.status||'pending']:'Завантаження не завершено')}</span></div><div class="creative-version-list">${g.versions.map(f=>`<button data-creative-view="${h(f.id)}" ${f.status==='ready'?'':'disabled'}>V${f.assetVersion} · ${h(f.name)}</button>`).join('')}</div>${g.versions.filter(f=>f.status==='ready').length>1?`<button data-creative-compare="${h(g.id)}">Порівняти версії</button>`:''}${work?`<label class="file-drop">+ Нова версія<input type="file" data-creative-file="${h(g.id)}" accept=".png,.jpg,.jpeg,.webp,.gif,.mp4,.pdf"></label>`:''}${g.latest.review?.note?`<p>${h(g.latest.review.note)}</p>`:''}</article>`).join('')||'<p class="empty">Додай матеріал для версій і погодження.</p>'}${work?'<label class="file-drop">+ Новий креатив<input type="file" data-creative-file="" accept=".png,.jpg,.jpeg,.webp,.gif,.mp4,.pdf"></label>':''}</section>`;
}
export function mountCreativeReview(root,{getTask,getActor,upload,fetchFile,action,notice}){
 let dialog,urls=[];function cleanup(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[];dialog?.remove();dialog=null;}
 async function view(group,fileId,compare=false,pairedId){cleanup();const task=getTask(),ready=group.versions.filter(f=>f.status==='ready');if(!ready.length)return;
  const current=ready.find(f=>f.id===fileId)||ready.at(-1),previous=ready.find(f=>f.id===pairedId&&f.id!==current.id)||ready.filter(f=>f.id!==current.id).at(-1);
  dialog=document.createElement('dialog');const d=dialog;d.className='creative-viewer';document.body.append(d);d.innerHTML=`<div class="dialog-head"><h2>Перегляд креативу</h2><button data-close aria-label="Закрити">×</button></div><p role="status">Завантаження…</p>`;d.showModal();d.querySelector('[data-close]').onclick=cleanup;d.addEventListener('close',cleanup,{once:true});
  const files=compare&&previous?[previous,current]:[current];
  try{const media=await Promise.all(files.map(async f=>({f,blob:await fetchFile(f)})));if(dialog!==d)return;const local=media.map(({f,blob})=>{const url=URL.createObjectURL(blob);urls.push(url);return {f,url};});
   d.innerHTML=`<div class="dialog-head"><h2>${h(group.versions[0].name)}</h2><button data-close aria-label="Закрити">×</button></div><div class="creative-compare ${local.length>1?'two-up':''}">${local.map(({f,url},i)=>`<section><label>Версія<select data-version-select="${i}">${ready.map(v=>`<option value="${h(v.id)}" ${v.id===f.id?'selected':''}>V${v.assetVersion} · ${h(v.name)}</option>`).join('')}</select></label><div class="creative-media" data-file-id="${h(f.id)}">${previewKind(f.mime)==='image'?`<div class="creative-image"><img src="${url}" alt="${h(f.name)}"><div class="creative-pins"></div></div>`:previewKind(f.mime)==='video'?`<video controls preload="metadata" src="${url}" aria-label="${h(f.name)}"></video>`:`<iframe sandbox title="${h(f.name)}" src="${url}"></iframe><a href="${url}" download="${h(f.name)}">Завантажити PDF</a>`}</div><p class="task-help">${previewKind(f.mime)==='image'?'Натисни на зображення, щоб прив’язати коментар до точки.':previewKind(f.mime)==='video'?'Коментар збережеться з поточним таймкодом.':'Коментарі прив’язані до цієї версії PDF.'}</p><div data-version-status="${h(f.id)}"></div><div data-version-comments="${h(f.id)}"></div>${task.permissions?.comment?`<form data-creative-comment="${h(f.id)}"><span data-point-label></span><textarea name="text" aria-label="Коментар до V${f.assetVersion}" rows="3" maxlength="10000" required></textarea><button type="submit">Додати коментар до V${f.assetVersion}</button></form>`:''}${getActor().role==='owner'&&f.id===group.latest.id?`<form data-creative-review="${h(f.id)}"><label>Рішення<select name="status"><option value="approved">Погодити цю версію</option><option value="changes">На доопрацювання</option></select></label><label>Коментар до рішення<textarea name="text" rows="3" maxlength="10000"></textarea></label><button type="submit">Зберегти рішення щодо V${f.assetVersion}</button></form>`:''}</section>`).join('')}</div>${local.length===2&&files.every(f=>f.mime==='video/mp4')?'<button data-sync-video>Відтворити обидві версії разом</button>':''}<p class="creative-error" role="alert"></p>`;
   d.querySelector('[data-close]').onclick=cleanup;
   function renderFeedback(){for(const f of files){const fresh=getTask()?.attachments.find(x=>x.id===f.id)||f;d.querySelector(`[data-version-status="${f.id}"]`).textContent=`V${fresh.assetVersion}: ${reviewLabels[fresh.review?.status||'pending']}${fresh.review?.by?' · '+fresh.review.by:''}${fresh.review?.note?' · '+fresh.review.note:''}`;d.querySelector(`[data-version-comments="${f.id}"]`).innerHTML=(fresh.reviewComments||[]).map((c,i)=>`<article class="creative-comment"><strong>${h(c.author)}</strong>${c.x!=null?` · точка ${i+1}`:c.time!=null?` · ${Math.floor(c.time/60)}:${String(Math.floor(c.time%60)).padStart(2,'0')}`:''}<p>${h(c.text)}</p></article>`).join('');const pins=d.querySelector(`[data-file-id="${f.id}"] .creative-pins`);if(pins){pins.replaceChildren();(fresh.reviewComments||[]).forEach((c,i)=>{if(c.x==null)return;const pin=document.createElement('span');pin.className='creative-pin';pin.textContent=i+1;pin.style.left=c.x+'%';pin.style.top=c.y+'%';pin.title=c.author+': '+c.text;pins.append(pin);});}}}
   renderFeedback();
   d.querySelectorAll('[data-version-select]').forEach(select=>select.onchange=()=>{const id=select.value,selected=group.versions.find(f=>f.id===id);const otherId=files[Number(select.dataset.versionSelect)===0?1:0]?.id;if(files.length===1)view(group,id);else viewPair(group,otherId,id);});
   async function viewPair(g,left,right){await view(g,right,true,left);}
   for(const {f}of local){let point;const img=d.querySelector(`[data-file-id="${f.id}"] img`),form=d.querySelector(`[data-creative-comment="${f.id}"]`);if(img&&form)img.onclick=e=>{const r=img.getBoundingClientRect();point={x:Math.round((e.clientX-r.left)/r.width*10000)/100,y:Math.round((e.clientY-r.top)/r.height*10000)/100};form.querySelector('[data-point-label]').textContent=`Точка: ${point.x}% / ${point.y}%`;};if(form)form.onsubmit=async e=>{e.preventDefault();const video=d.querySelector(`[data-file-id="${f.id}"] video`);const values={op:'comment',attachmentId:f.id,text:new FormData(form).get('text'),...(point||{}),...(video?{time:Math.round(video.currentTime*100)/100}:{})};await send(values,form);point=null;form.querySelector('[data-point-label]').textContent='';};const review=d.querySelector(`[data-creative-review="${f.id}"]`);if(review)review.onsubmit=e=>{e.preventDefault();send({op:'review',attachmentId:f.id,...Object.fromEntries(new FormData(review))},review);};}
   async function send(values,form){const b=form.querySelector('button');b.disabled=true;try{const ok=await action(values);if(ok!==false){form.reset();renderFeedback();d.querySelector('.creative-error').textContent='Збережено';}}catch(e){d.querySelector('.creative-error').textContent=e.message;}finally{b.disabled=false;}}
   d.querySelector('[data-sync-video]')?.addEventListener('click',async()=>{const [a,b]=d.querySelectorAll('video');b.currentTime=a.currentTime;try{await Promise.all([a.play(),b.play()]);}catch{d.querySelector('.creative-error').textContent='Запусти відео кнопками плеєрів';}a.ontimeupdate=()=>{if(Math.abs(a.currentTime-b.currentTime)>.3)b.currentTime=a.currentTime;};a.onpause=()=>b.pause();});
  }catch(e){if(dialog===d)d.querySelector('[role=status]').textContent=e.message;}
 }
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const groups=creativeGroups(getTask());if(b.dataset.creativeView){const group=groups.find(g=>g.versions.some(f=>f.id===b.dataset.creativeView));if(group)view(group,b.dataset.creativeView);}if(b.dataset.creativeCompare){const group=groups.find(g=>g.id===b.dataset.creativeCompare);if(group)view(group,null,true);}});
 root.addEventListener('change',e=>{if(e.target.matches('[data-creative-file]')&&e.target.files[0])upload(e.target.files[0],e.target.dataset.creativeFile,true);});
 document.querySelector('#task-dialog')?.addEventListener('close',cleanup);
 return {cleanup};
}
