import {escapeHtml as h} from './metrics.js';import {inboxItems} from './inbox-model.js';
export function mountInbox(root,{actor,request,openTask,onData,notice,isActive=()=>true}){
 let filter=actor.role==='owner'?'priority':'unread',busy=false,data;
 async function refresh(){try{data=await request({op:'list'});if(!root.isConnected||!isActive())return;onData(data);render();}catch(e){if(!root.isConnected||!isActive())return;notice(e.message);root.innerHTML='<p>Не вдалося отримати Inbox.</p><button data-inbox-refresh>Оновити</button>';}}
 function render(){const items=inboxItems(data.tasks,actor,data.preferences),visible=items.filter(i=>filter==='snoozed'?i.snoozed:!i.snoozed&&(filter==='all'||filter==='unread'&&!i.read||filter==='priority'&&i.urgent));
  root.innerHTML=`<div class="space-toolbar inbox-toolbar">${[['priority','Потребує рішення'],['unread','Непрочитані'],['all','Усі'],['snoozed','Відкладені']].map(([id,title])=>`<button data-inbox-filter="${id}" aria-pressed="${filter===id}">${title} · ${items.filter(i=>id==='snoozed'?i.snoozed:!i.snoozed&&(id==='all'||id==='unread'&&!i.read||id==='priority'&&i.urgent)).length}</button>`).join('')}<button data-inbox-refresh>Оновити</button></div><p class="task-help">Персональна черга доступних тобі задач. Нова зміна повертає задачу з відкладених і позначає її непрочитаною.</p><div class="inbox-list">${visible.map(i=>`<article class="inbox-item ${i.read?'read':''}"><div><span class="creative-status">${h(i.reasons[0])}</span><h2><button data-inbox-open="${h(i.task.id)}">${h(i.task.title)}</button></h2><p>${h(i.task.assignee)} · ${h(i.task.due||'без дедлайну')}</p><small>${i.reasons.map(h).join(' · ')}</small>${i.snoozed?`<p>Відкладено до ${h(new Date(i.pref.snoozeUntil).toLocaleString('uk-UA',{timeZone:'Europe/Kyiv'}))}</p>`:''}</div><div class="inbox-actions"><button data-inbox-action="${i.read?'unread':'read'}" data-task-id="${h(i.task.id)}">${i.read?'Позначити непрочитаною':'Прочитано'}</button>${i.snoozed?`<button data-inbox-action="unsnooze" data-task-id="${h(i.task.id)}">Повернути зараз</button>`:`<select data-snooze="${h(i.task.id)}" aria-label="Відкласти ${h(i.task.title)}"><option value="">Нагадати пізніше…</option value="1">Через годину</option><option value="24">Через добу</option><option value="168">Через тиждень</option></select>`}</div></article>`).join('')||'<article class="space-card"><h2>Черга порожня</h2><p>У цьому фільтрі немає задач.</p></article>'}</div>`;
 }
 async function change(op,id,values={}){if(busy)return;const task=data.tasks.find(t=>t.id===id);if(!task)return;busy=true;try{await request({op,id,version:task.version,...values});await refresh();}catch(e){notice(e.message);}finally{busy=false;}}
 root.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.inboxFilter){filter=b.dataset.inboxFilter;render();}if(b.hasAttribute('data-inbox-refresh'))refresh();if(b.dataset.inboxOpen)openTask(b.dataset.inboxOpen);if(b.dataset.inboxAction)change(b.dataset.inboxAction,b.dataset.taskId);};
 root.onchange=e=>{if(e.target.dataset.snooze&&e.target.value)change('snooze',e.target.dataset.snooze,{hours:Number(e.target.value)});};
 refresh();return {refresh};
}
