import {mountWhiteboard} from './whiteboard.js';
import {dependencyState,validateDependencies,launchReadiness,gateNames,iceScore,rankExperiments,deadlineQueue,moveCard} from './mechanics-model.js';
import {validMonth,previousMonth,reportReadiness,linkedTasks,parseChannelCsv,channelCsvTemplate} from './monthly-model.js';
import {escapeHtml as h} from './metrics.js';
import {channelMetrics,funnelStages,budgetSummary} from './analytics-model.js';
import {teamWorkload,roleLabels,roleAccess} from './team-model.js';
import {modules,templates,extraLabels,choices,emptyPayload,rowsFor,replaceRows,recordTitle,safeLink,parseImport,mergeDocument,validatePayload,reportMetrics} from './space-model.js';
const sections=modules;
const labels={name:'Назва',title:'Назва',stage:'Етап',progress:'Прогрес, %',budget:'Бюджет',owner:'Відповідальний',due:'Дедлайн',tone:'Позначка',day:'День',status:'Статус',channel:'Канал',pillar:'Напрям',format:'Формат',objective:'Мета',hook:'Початок / хук',cta:'Заклик до дії',gates:'Готовність',brief:'Бриф',copy:'Текст',visual:'Візуал',approval:'Погодження',tracking:'Відстеження',context:'Контекст',requester:'Ініціатор',priority:'Пріоритет',impact:'Вплив',risk:'Ризик',recommendation:'Рекомендація',outcome:'Результат',related:'Пов’язане',month:'Місяць',spend:'Витрати',impressions:'Покази',clicks:'Кліки',users:'Користувачі',sessions:'Сесії',coverage:'Покриття',leads:'Ліди',validLeads:'Валідні ліди',connections:'Підключення',revenue:'Дохід',source:'Джерело',note:'Примітка',done:'Завершено'};
const defaults={campaigns:{name:'',stage:'План',progress:0,budget:'',owner:'',due:'',tone:''},content:{title:'',day:1,status:'План',owner:'',channel:'',pillar:'',format:'',objective:'',hook:'',cta:'',due:'',gates:{brief:false,copy:false,visual:false,approval:false,tracking:false}},decisions:{title:'',context:'',owner:'',status:'Потребує рішення',requester:'',due:'',priority:'Medium',impact:'',risk:'',recommendation:'',outcome:'',related:''},reports:{month:'',status:'Чернетка',spend:null,impressions:null,clicks:null,users:null,sessions:null,coverage:null,leads:null,validLeads:null,connections:null,revenue:null,source:'',note:''}};
Object.assign(labels,extraLabels);
Object.assign(defaults,templates);
const linkedModules=new Set(['campaigns','launches','content','decisions','execution','roadmap','insights','experiments']);
for(const key of linkedModules)defaults[key].taskIds=[];
labels.taskIds='Пов’язані командні задачі';
labels.dependencies='Передумови плану / задачі';labels.requiredGates='Обов’язкові підтвердження запуску';
defaults.execution.dependencies=[];defaults.launches.requiredGates=Object.keys(gateNames);defaults.launches.status='Підготовка';defaults.launches.planIds=[];labels.planIds='Передумови у плані виконання';
for(const k of ['impact','confidence','ease'])defaults.experiments[k]=null;

export function applyEdits(original,entries){
 const record=structuredClone(original);
 for(const {key,value,type} of entries){
  if(key==='id')continue;
  if(type==='number'){if(value.trim()===''||!Number.isFinite(Number(value)))throw Error('Заповни числові поля');record[key]=Number(value);}
  else if(type==='boolean')record[key]=value===true;
  else if(type==='object')record[key]=JSON.parse(value);
  else record[key]=value;
 }
 return record;
}
const numberFields=new Set(['planned','actual','targetLeads','actualLeads','targetConnections','actualConnections','capacity','allocated','envelope','impressions','clicks','users','sessions','coverage','spend','visits','leads','validLeads','connections','revenue','promoCost','margin','retention','target','confidence','ease','impact','progress']);
const statusChoices={reports:['Чернетка','Частково','Перевірено'],insights:['Новий','Перевіряємо','Підтверджено','Відхилено'],roadmap:['Заплановано','У роботі','Заблоковано','Готово'],budget:['Чернетка','Погоджено','Активно','Стоп'],promos:['Потрібні дані','На оцінці','Погоджено','Завершити'],rhythm:['Заплановано','Сьогодні','Очікує','Готово'],experiments:['Backlog','Готовий','Запущено','Завершено'],execution:['До роботи','У роботі','Заблоковано','Готово'],automations:['Очікує налаштування','Очікує доступ','Заблоковано','Готово','Активно'],launches:['Підготовка','Готово до запуску','Запущено','Завершено'],report_requests:['Очікуємо','Отримано','Перевірено']};
export function mountOwnerSpace({request,backupStatus=async()=>null,notice,getTasks=()=>[],getTeam=()=>[],openTask=()=>{},openAssignee=()=>{}}){
 const root=document.querySelector('#owner-space'),nav=document.querySelector('#owner-nav');
 let actor,key,documents=[],fetching=false,part='lines',filter='',reportId,month=previousMonth();
 const views={monthly:'Збір звітів',team:'Команда',overview:'Огляд CMO',review:'Рев’ю керівника',strategy:'Стратегія',analytics:'Аналітика',funnel:'Воронка',deadlines:'Контроль дедлайнів',sources:'Джерела даних'};
 const groups=[['Робота',['campaigns','launches','content','decisions','execution','legacy_tasks']],['Планування',['roadmap','budget','promos','rhythm','team_ops']],['Дослідження й дані',['insights','experiments','attribution','reports','report_requests']],['Інструменти',['visual','automations']]];
 nav.innerHTML='<small>ПРОСТІР КЕРІВНИКА</small>'+Object.entries(views).map(([k,label])=>`<button data-space="${k}">${h(label)}</button>`).join('')+groups.map(([label,keys])=>`<details ${label==='Робота'?'open':''}><summary>${label}</summary>${keys.map(k=>`<button data-space="${k}">${h(sections[k])}</button>`).join('')}</details>`).join('')+'<button data-space="transfer">Експорт / імпорт</button>';
 const dialog=document.createElement('dialog');dialog.innerHTML='<div class="dialog-head"><h2></h2><button type="button" data-close aria-label="Закрити">×</button></div><div class="space-dialog-body"></div><p class="space-error" role="status"></p>';document.body.append(dialog);
 const body=dialog.querySelector('.space-dialog-body'),error=dialog.querySelector('.space-error');
 dialog.querySelector('[data-close]').onclick=()=>dialog.close();
 function open(title){error.textContent='';dialog.querySelector('h2').textContent=title;if(!dialog.open)dialog.showModal();}
 function doc(k=key){return documents.find(d=>d.key===k);}
 function payload(){return doc()?.payload??emptyPayload(key);}
 function rows(){return rowsFor(key,payload(),part);}
 function valueMarkup(k,v){
  if(k==='taskIds'){const linked=linkedTasks({taskIds:v},getTasks());return '<div class="linked-tasks">'+linked.tasks.map(t=>`<button data-open-task="${h(t.id)}">${h(t.title)} · ${h(t.assignee)} · ${h(t.lane)}</button>`).join('')+(linked.unavailable.length?`<p>Задач недоступно: ${linked.unavailable.length}. Зв’язки збережено.</p>`:'')+'</div>';}

  if(v===null||v===undefined||v==='')return '';
  if(typeof v==='boolean')return `<div class="space-value"><span>${h(labels[k]||k)}</span><p>${v?'Так':'Ні'}</p></div>`;
  if(typeof v==='object')return `<details class="space-nested"><summary>${h(labels[k]||k)}</summary>${Array.isArray(v)?v.map(r=>typeof r==='object'?`<article><strong>${h(recordTitle(r))}</strong>${Object.entries(r).filter(([a])=>!['id','title','name','src'].includes(a)).map(([a,b])=>valueMarkup(a,b)).join('')}${r.src&&safeLink(r.src)?`<a href="${h(safeLink(r.src))}" target="_blank" rel="noopener noreferrer">Відкрити зображення</a>`:''}</article>`:`<p>${h(r)}</p>`).join(''):Object.entries(v).map(([a,b])=>valueMarkup(a,b)).join('')}</details>`;
  const link=['url','src','linked'].includes(k)?safeLink(v):null;
  return `<div class="space-value"><span>${h(labels[k]||k)}</span><p>${link?`<a href="${h(link)}" target="_blank" rel="noopener noreferrer">${h(v)}</a>`:h(v)}</p></div>`;
 }
 function card(r,i){return `<article class="space-card"><h2>${h(recordTitle(r))}</h2><div class="metadata">${[r.owner,r.stage||r.status||r.approval,r.due||r.deadline].filter(Boolean).map(v=>`<span>${h(v)}</span>`).join('')}</div>${mechanicsMarkup(r)}${Object.entries(r).filter(([k])=>!['id','name','title','month','owner','stage','status','due','deadline','tone'].includes(k)).map(([k,v])=>valueMarkup(k,v)).join('')}<button data-edit="${i}">Відкрити / редагувати</button></article>`;}
 function render(){
  if(key==='transfer'){renderTransfer();return;}
  if(key==='monthly'){renderMonthly();return;}
  if(views[key]){renderSummary();return;}
  if(key==='visual'){renderBoards();return;}
  const d=doc(),items=rows();if(!Array.isArray(items))throw Error('Непідтримуваний формат розділу');
  const source=d?.source==='cmo-space-v29'?'Дані перенесено з CMO Space.':d?.source==='rebuilt-empty'?'Розділ перебудовано. Старі локальні записи не відновлено; нові записи зберігаються у спільній базі.':'Дані Workspace.';
  const notes={reports:'Збережено вихідні статуси та примітки. Неповні дані потребують перевірки.',legacy_tasks:'Старі записи для звірки; вони не додані до командного задачника.',automations:'Це реєстр налаштувань і підтверджених запусків. Записи тут самі не запускають нагадування чи інтеграції.',team_ops:'План завантаження. Редагування цих записів не змінює права доступу команди.',rhythm:'План зустрічей і результатів. Нагадування ще не налаштовано.'};
  root.innerHTML=`<div class="space-toolbar"><p>${items.length} записів · версія ${d?.revision||0}</p><button data-refresh>Оновити розділ</button><button data-history>Історія</button><button data-export>Повна копія</button>${key!=='legacy_tasks'?'<button class="primary" data-add>+ Додати</button>':''}</div><p class="space-source">${source} ${notes[key]||''}</p>${key==='budget'?`<div class="space-toolbar"><button data-part="lines">Статті бюджету</button><button data-part="resources">Ресурси</button><span>Ліміт: ${payload().envelope==null?'не задано':h(payload().envelope)+' грн'}</span><button data-envelope>Задати ліміт</button></div>`:''}<label class="space-search">Знайти запис<input data-search value="${h(filter)}" placeholder="Назва, відповідальний, статус…"></label><div class="space-grid">${(key==='experiments'?rankExperiments(items):items).map(r=>({r,i:items.indexOf(r)})).filter(({r})=>JSON.stringify(r).toLocaleLowerCase('uk').includes(filter.toLocaleLowerCase('uk'))).map(({r,i})=>card(r,i)).join('')||'<p>Записів немає. Додай перший запис або імпортуй збережений експорт.</p>'}</div>`;
 }
 async function refresh(){if(fetching)return;fetching=true;try{const r=await request({op:'list'});documents=r.documents;render();notice();return true;}catch(e){notice(e.message);root.innerHTML='<p>Не вдалося отримати дані.</p><button data-refresh>Спробувати ще раз</button>';}finally{fetching=false;}}
 function fieldsMarkup(value,path=[],editKey=key){return Object.entries(value).filter(([k])=>k!=='id').map(([k,v])=>{
  const next=[...path,k],attr=`data-path="${h(JSON.stringify(next))}"`,label=h(labels[k]||k);
  if(k==='taskIds'){const known=new Set(getTasks().map(t=>t.id));return `<label>${label}<select ${attr} data-type="taskIds" multiple size="6">${getTasks().map(t=>`<option value="${h(t.id)}" ${v.includes(t.id)?'selected':''}>${h(t.title)} · ${h(t.assignee)} · ${h(t.lane)}</option>`).join('')}${v.filter(id=>!known.has(id)).map(id=>`<option selected value="${h(id)}">Недоступна задача · ${h(id)}</option>`).join('')}</select><small>Обери пов’язані задачі. Зв’язок не змінює їхній статус або відповідального.</small></label>`;}
  if(['dependencies','planIds'].includes(k)&&Array.isArray(v)){const available=k==='planIds'?rowsFor('execution',doc('execution')?.payload||[]):[...rowsFor(editKey,doc(editKey)?.payload||[]),...getTasks()].filter(r=>r.id!==value.id);return `<label>${label}<select ${attr} data-type="taskIds" multiple size="6">${available.map(r=>`<option value="${h(r.id)}" ${v.includes(r.id)?'selected':''}>${h(recordTitle(r))}</option>`).join('')}${v.filter(id=>!available.some(r=>r.id===id)).map(id=>`<option selected value="${h(id)}">Не знайдено · ${h(id)}</option>`).join('')}</select></label>`;}
  if(k==='requiredGates')return `<label>${label}<select ${attr} data-type="taskIds" multiple size="7">${Object.entries(gateNames).map(([id,title])=>`<option value="${id}" ${v.includes(id)?'selected':''}>${h(title)}</option>`).join('')}</select><small>Обери застосовні підтвердження для цього запуску.</small></label>`;
  if(k==='month')return `<label>${label}<input ${attr} data-type="string" type="month" value="${h(v||'')}"></label>`;
  if(k!=='cards'&&Array.isArray(v)&&v.every(r=>typeof r==='string'))return `<label>${label}<textarea ${attr} data-type="strings" rows="3">${h(v.join('\n'))}</textarea><small>Один пункт на рядок</small></label>`;
  if(v&&typeof v==='object')return `<fieldset><legend>${label}</legend>${Array.isArray(v)?v.map((r,i)=>`<details open><summary>${h(recordTitle(r))}</summary>${fieldsMarkup(r,[...next,i],editKey)}</details>`).join(''):fieldsMarkup(v,next,editKey)}${k==='cards'?'<button type="button" data-add-note>+ Нотатка</button>':''}</fieldset>`;
  const type=typeof v==='boolean'?'boolean':typeof v==='number'||v===null&&numberFields.has(k)?'number':'string';
  if(type==='boolean')return `<label class="check"><input ${attr} data-type="boolean" type="checkbox" ${v?'checked':''}>${label}</label>`;
  if(type==='number')return `<label>${label}<input ${attr} data-type="number" data-nullable="${v===null}" type="number" step="any" value="${v===null?'':h(v)}" ${v===null?'':'required'}></label>`;
  const options=k==='status'?statusChoices[editKey]:choices[k];
  if(options)return `<label>${label}<select ${attr} data-type="string">${[...new Set([String(v??''),...options])].map(x=>`<option ${x===v?'selected':''}>${h(x)}</option>`).join('')}</select></label>`;
  return `<label>${label}<textarea ${attr} data-type="string" rows="2">${h(v??'')}</textarea></label>`;
 }).join('');}
 function readForm(form,original){const edited=structuredClone(original);for(const el of form.querySelectorAll('[data-path]')){const path=JSON.parse(el.dataset.path);if(path.some(k=>['__proto__','constructor','prototype'].includes(k)))throw Error('Неприпустиме поле');let holder=edited;for(const k of path.slice(0,-1))holder=holder[k];const k=path.at(-1);if(el.dataset.type==='taskIds')holder[k]=[...el.selectedOptions].map(o=>o.value);else if(el.dataset.type==='number'){if(!el.value.trim()){if(el.dataset.nullable==='true')holder[k]=null;else throw Error('Заповни числові поля');}else{if(!Number.isFinite(Number(el.value)))throw Error('Перевір число');holder[k]=Number(el.value);}}else if(el.dataset.type==='boolean')holder[k]=el.checked;else if(el.dataset.type==='strings')holder[k]=el.value.split('\n').map(v=>v.trim()).filter(Boolean);else holder[k]=el.value;}return edited;}
 function edit(index,prefill={}){
  const editKey=key,editPart=part,d=doc(),revision=d?.revision||0,base=structuredClone(payload()),items=structuredClone(rows()),template=key==='budget'&&part==='resources'?'resources':key;
  let original=index===null?{id:crypto.randomUUID(),...structuredClone(defaults[template]),...prefill}:{...structuredClone(defaults[template]||{}),...(linkedModules.has(key)?{taskIds:[]}:{}),...items[index]};
  body.innerHTML='<form class="space-editor"></form>';const form=body.querySelector('form');open(index===null?'Новий запис':'Редагування запису');
  function draw(){form.innerHTML=fieldsMarkup(original,[],editKey)+'<button>Зберегти</button>';}
  draw();form.addEventListener('click',e=>{if(e.target.closest('[data-add-note]')){try{original=readForm(form,original);original.cards.push({id:crypto.randomUUID(),...structuredClone(templates.cards)});draw();}catch(e){error.textContent=e.message;}}});
  form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button:not([type=button])');button.disabled=true;error.textContent='';try{
   const edited=readForm(form,original);if(!String(edited.title||edited.name||edited.month||edited.source||edited.pack||edited.role||'').trim())throw Error('Заповни назву запису');
   if(editKey==='visual')edited.updated=new Date().toISOString();
   if(editKey==='reports'&&edited.status==='Перевірено'){const readiness=reportReadiness(edited);if(readiness.missing.length)throw Error(readiness.missing.join(' · '));if(readiness.warnings.length&&!String(edited.note||'').trim())throw Error(readiness.warnings.join(' · ')+' · Поясни різницю періодів або когорт у примітці');}
   if(editKey==='attribution'&&edited.month&&!validMonth(edited.month))throw Error('Перевір звітний місяць');
   const nextItems=index===null?[...items,edited]:items.map((r,i)=>i===index?edited:r);
   if(['roadmap','execution'].includes(editKey)){validateDependencies(nextItems,getTasks());if(edited.status==='Готово'&&!dependencyState(edited,nextItems,getTasks()).ready)throw Error('Спочатку заверши передумови плану');}
   if(editKey==='experiments'&&['impact','confidence','ease'].some(k=>edited[k]!=null)&&iceScore(edited)===null)throw Error('Для ICE заповни всі три оцінки від 1 до 10');
   if(editKey==='launches'&&['Готово до запуску','Запущено'].includes(edited.status)&&!launchReadiness(edited,getTasks(),rowsFor('execution',doc('execution')?.payload||[])).ready)throw Error('Запуск має непідтверджені передумови, задачі або погодження');
   const next=replaceRows(editKey,base,nextItems,editPart);validatePayload(editKey,next);
   await request({op:'save',key:editKey,revision,payload:next});dialog.close();await refresh();notice('Збережено');
  }catch(e){error.textContent=e.message+' Введені зміни залишилися у формі.';}finally{button.disabled=false;}};
 }
 async function exportAll(){try{const packet=await request({op:'export'}),blob=new Blob([JSON.stringify(packet,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pavutyna-cmo-full-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Повну копію підготовлено: розділи та командні задачі.');}catch(e){notice(e.message);}}
 async function history(){open('Історія розділу');body.textContent='Завантаження…';try{const data=await request({op:'history',key});body.innerHTML=(data.events||[]).map(e=>`<details><summary>Версія ${h(e.revision)} · ${h(new Date(e.created_at).toLocaleString('uk-UA'))}</summary>${rowsFor(key,e.payload,part).map(r=>`<article><h3>${h(recordTitle(r))}</h3>${Object.entries(r).filter(([k])=>k!=='id').map(([k,v])=>valueMarkup(k,v)).join('')}</article>`).join('')}${key==='budget'?valueMarkup('envelope',e.payload.envelope):''}</details>`).join('')||'<p>Після першого збереження тут з’явиться історія. Початкову копію збережено окремо.</p>';}catch(e){error.textContent=e.message;}}
 function envelope(){const d=doc(),revision=d?.revision||0,base=structuredClone(payload());open('Ліміт бюджету');body.innerHTML=`<form><label>Ліміт, грн<input name="envelope" type="number" min="0" step="any" value="${base.envelope==null?'':h(base.envelope)}" required></label><button>Зберегти</button></form>`;body.querySelector('form').onsubmit=async e=>{e.preventDefault();try{base.envelope=Number(new FormData(e.target).get('envelope'));await request({op:'save',key:'budget',revision,payload:base});dialog.close();await refresh();}catch(e){error.textContent=e.message;}};}
 function renderSummary(){
  const list=k=>rowsFor(k,doc(k)?.payload??emptyPayload(k)),reports=list('reports'),decisions=list('decisions'),launches=list('launches'),tasks=getTasks();
  const blocks=(label,items)=>`<article class="space-card"><h2>${h(label)}</h2>${items.length?items.map(r=>`<div class="space-value">${tasks.some(t=>t.id===r.id)?`<button data-open-task="${h(r.id)}">${h(recordTitle(r))}</button>`:`<strong>${h(recordTitle(r))}</strong>`}<p>${h(r.owner||r.assignee||'')} · ${h(r.status||r.lane||r.approval||'')}</p></div>`).join(''):'<p>Записів немає</p>'}</article>`;
  const metric=(label,value)=>`<div class="stat"><strong>${value==null?'—':h(typeof value==='number'?new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(value):value)}</strong><span>${h(label)}</span></div>`;
  const toolbar='<div class="space-toolbar"><button data-refresh>Оновити</button><button data-export>Повна копія</button></div>';
  if(key==='deadlines'){const q=deadlineQueue(tasks);root.innerHTML=toolbar+'<p class="space-source">Точні дати — за часовим поясом Києва. Довільні строки потребують уточнення; завершені задачі виключено. Ранковий контроль у ChatGPT увімкнено по буднях.</p><div class="space-grid">'+[['Прострочені',q.overdue],['Сьогодні',q.today],['Найближчі 2 дні',q.soon],['На перевірці',q.review],['Заблоковані',q.blocked],['Уточнити дату',q.undated]].map(([label,items])=>blocks(label,items)).join('')+'</div>';return;}
  if(key==='team'){
   const people=teamWorkload(getTeam(),tasks);
   root.innerHTML=toolbar+'<p class="space-source">Навантаження за наявними задачами. Ролі беруться з чинного доступу; завершені задачі залишаються в історії.</p><div class="team-grid">'+people.map(p=>`<article class="space-card team-card"><div class="team-person"><span class="avatar">${h(p.name.slice(0,1))}</span><div><h2>${h(p.name)}</h2><span class="team-role">${p.active?h(roleLabels[p.role]||p.role):'Немає активного доступу'}</span></div></div><p class="team-access">${p.active?h(roleAccess[p.role]):'Збережено призначені задачі. Активного учасника з цим ім’ям у Workspace немає.'}</p><div class="team-counts"><span><strong>${p.open}</strong> відкритих</span><span><strong>${p.review}</strong> на перевірці</span><span><strong>${p.blocked}</strong> блокувань</span><span><strong>${p.done}</strong> завершених</span></div>${p.overdue?`<p class="team-overdue">Прострочено: ${p.overdue}</p>`:''}<div class="team-task-list">${p.tasks.slice(0,4).map(t=>`<button data-open-task="${h(t.id)}"><span>${h(t.title)}</span><small>${h(t.due)}</small></button>`).join('')||'<p>Відкритих задач немає</p>'}</div><button data-assignee="${h(p.name)}">Відкрити задачі · ${p.total}</button></article>`).join('')+'</div>';return;
  }
  if(['overview','review'].includes(key)){root.innerHTML=toolbar+`<div class="stats">${metric('Відкриті задачі',tasks.filter(t=>t.lane!=='done').length)}${metric('На перевірці',tasks.filter(t=>t.lane==='review').length)}${metric('Заблоковані',tasks.filter(t=>t.lane==='blocked').length)}${metric('Перевірені звіти',reports.filter(r=>r.status==='Перевірено').length)}</div><div class="space-grid">${blocks('Потребують рішення',decisions.filter(r=>!['Погоджено','Прийнято','Вирішено','Закрито','Відхилено'].includes(r.status)))}${blocks('Перевірити результати',tasks.filter(t=>['review','blocked'].includes(t.lane)))}${blocks('Звіти для звірки',reports.filter(r=>r.status!=='Перевірено'))}${blocks('Запуски до погодження',launches.filter(r=>r.approval!=='Погоджено'))}</div>`;return;}
  if(key==='strategy'){const roadmap=list('roadmap');root.innerHTML=toolbar+'<p class="space-source">План дій за горизонтами та підтверджені інсайти. Оновлюй їх у розділах «План на 90 днів» та «Інсайти».</p><div class="space-grid">'+['0–30','31–60','61–90'].map(horizon=>blocks(horizon+' днів',roadmap.filter(r=>r.horizon===horizon))).join('')+blocks('Підтверджені інсайти',list('insights').filter(r=>r.status==='Підтверджено'))+'</div>';return;}
  if(key==='sources'){renderTransfer();root.querySelector('[data-import]')?.closest('label').remove();root.insertAdjacentHTML('afterbegin','<p class="space-source">Перенесено серверні записи CMO Space та 85 початкових задач Workflow. Для інших модулів створено нову структуру. Дані з браузера не підмінено прикладами зі старого коду.</p>');return;}
  const report=reports.find(r=>r.id===reportId)||reports.slice().sort((a,b)=>String(b.month).localeCompare(String(a.month)))[0],m=reportMetrics(report),format=v=>v==null?'—':new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(v);
  root.innerHTML=toolbar+`<label class="space-search">Місячний звіт<select data-report-select>${reports.map(r=>`<option value="${h(r.id)}" ${r.id===report?.id?'selected':''}>${h(r.month)} · ${h(r.status)}</option>`).join('')}</select></label><p class="space-source">${m?'Розрахунки за звітом зі статусом «Перевірено».':'Звіт не перевірено. Показники ефективності не розраховуються; нижче — вихідні значення для звірки.'}</p><div class="stats">${metric('CPL, грн',m?.cpl)}${metric('CPQL, грн',m?.cpql)}${metric('CAC, грн',m?.cac)}${metric('Лід → підключення, %',m?.leadToConnection)}${metric('CTR, %',m?.ctr)}</div><div class="space-grid"><article class="space-card"><h2>${h(report?.month||'Звітів немає')}</h2>${report?Object.entries(report).filter(([k])=>k!=='id').map(([k,v])=>valueMarkup(k,v)).join(''):''}</article><article class="space-card"><h2>${key==='funnel'?'Етапи воронки':'Аналітика каналів'}</h2>${key==='funnel'?(report?funnelStages(report).map(step=>`<div class="funnel-stage"><span>${h(step.label)}</span><strong>${step.value==null?'—':h(format(step.value))}</strong><small>${step.conversion==null?'Конверсія не визначена':h(format(step.conversion))+'% з попереднього етапу'}</small></div>`).join(''):'<p>Додай звіт</p>'):list('attribution').filter(r=>r.month===report?.month).map(r=>{const c=channelMetrics(r);return `<div class="channel-row"><h3>${h(r.source)}</h3><p>${h(r.quality)}</p>${[['CPL, грн',c?.cpl],['CPQL, грн',c?.cpql],['CAC, грн',c?.cac],['Лід → валідний, %',c?.validRate],['Валідний → підключення, %',c?.connectRate],['ROAS',c?.roas]].map(([label,value])=>`<div class="space-value"><span>${h(label)}</span><p>${h(format(value))}</p></div>`).join('')}${valueMarkup('note',r.note)}</div>`;}).join('')||'<p>Каналів за цей місяць немає. Додай дані через «Збір звітів».</p>'}</article></div>`
  if(key==='analytics'){const b=budgetSummary(doc('budget')?.payload);root.insertAdjacentHTML('beforeend',`<h2>Бюджет: усі статті плану</h2><div class="stats">${metric('План, грн',b.planned)}${metric('Факт, грн',b.actual)}${metric('Відхилення, грн',b.variance)}${metric('Залишок ліміту, грн',b.remaining)}</div><p class="space-source">Статей без фактичних витрат: ${b.unmeasured}. Неповні суми не розраховуються. Цей блок охоплює весь бюджетний план, без фільтра за місяцем звіту.</p><p class="space-source">Каналів без місяця: ${list('attribution').filter(r=>!r.month).length}. Їх можна доповнити у розділі «Атрибуція».</p><h2>Місячні звіти</h2><div class="table-scroll"><table><thead><tr><th>Місяць</th><th>Якість</th><th>CPL</th><th>CPQL</th><th>CAC</th><th>Лід → підключення</th></tr></thead><tbody>${reports.slice().sort((a,b)=>String(a.month).localeCompare(String(b.month))).map(r=>{const v=reportMetrics(r);return `<tr><td>${h(r.month)}</td><td>${h(r.status)}</td><td>${h(format(v?.cpl))}</td><td>${h(format(v?.cpql))}</td><td>${h(format(v?.cac))}</td><td>${h(format(v?.leadToConnection))}</td></tr>`;}).join('')}</tbody></table></div><p class="space-source">Показано канали лише за місяць обраного звіту. Витрати каналів не додаємо повторно до витрат місячного звіту.</p>`);}
 }

 function mechanicsMarkup(r){
  if(['roadmap','execution'].includes(key)){const d=dependencyState(r,rows(),getTasks());return `<div class="mechanics-state"><strong>${d.cycle?'Цикл залежностей':d.blocked?'Передумови не завершені':(r.dependencies||[]).length?'Передумови виконано':'Структурні залежності не задані'}</strong>${d.waiting.map(w=>`<p>${h(w.title)} · ${w.missing?'не знайдено':'очікує завершення'}</p>`).join('')}</div>`;}
  if(key==='launches'){const d=launchReadiness(r,getTasks(),rowsFor('execution',doc('execution')?.payload||[]));return `<div class="mechanics-state"><strong>${d.ready?'Готовий до запуску':'Не готовий до запуску'}</strong><p>Погодження: ${h(r.approval)}</p>${d.missing.map(g=>`<p>Підтвердити: ${h(gateNames[g]||g)}</p>`).join('')}<p>Незавершених / недоступних задач: ${d.pending.length} · передумов плану: ${d.pendingPlans.length}</p>${d.metadata.length?`<p>Заповнити: ${d.metadata.map(k=>h(labels[k]||k)).join(', ')}</p>`:''}</div>`;}
  if(key==='experiments')return `<div class="mechanics-state"><strong>ICE: ${iceScore(r)??'не оцінено'}</strong><p>Вплив × впевненість × простота; кожна оцінка 1–10. Порожні оцінки не підміняються середніми.</p></div>`;
  return '';
 }
 let boardSaving=false;
 function renderBoards(){
  const boards=rows(),selected=boards.find(b=>b.id===payload().active)||boards[0];
  root.onclick=null;
  root.innerHTML=`<div class="space-toolbar"><button data-refresh>Оновити</button><button data-add>+ Дошка</button>${selected?`<button data-edit="${boards.indexOf(selected)}">Назва / властивості</button>`:''}</div><div class="space-toolbar wb-tabs">${boards.map(b=>`<button data-board="${h(b.id)}" ${selected?.id===b.id?'aria-current="true"':''}>${h(b.name)}</button>`).join('')}</div><div class="whiteboard-root"></div>`;
  root.querySelectorAll('[data-board]').forEach(b=>b.onclick=()=>saveBoard(null,b.dataset.board));
  if(selected)mountWhiteboard(root.querySelector('.whiteboard-root'),{board:selected,save:saveBoard,notice,tasks:getTasks(),openTask});
  else root.querySelector('.whiteboard-root').textContent='Додай першу дошку, потім обери шаблон.';
 }
 async function saveBoard(next,active){if(boardSaving)return false;boardSaving=true;const d=doc('visual'),base=structuredClone(d.payload),revision=d.revision;try{const value=next?replaceRows('visual',base,rowsFor('visual',base).map(b=>b.id===next.id?{...next,updated:new Date().toISOString()}:b)):base;if(active)value.active=active;validatePayload('visual',value);await request({op:'save',key:'visual',revision,payload:value});await refresh();return true;}catch(e){notice(e.message+' Зміни дошки не збережено.');renderBoards();return false;}finally{boardSaving=false;}}

 function renderMonthly(){
  const reports=rowsFor('reports',doc('reports')?.payload||[]).filter(r=>r.month===month),channels=rowsFor('attribution',doc('attribution')?.payload||[]).filter(r=>r.month===month),requests=rowsFor('report_requests',doc('report_requests')?.payload||[]).filter(r=>r.status!=='Перевірено');
  root.innerHTML=`<div class="space-toolbar"><label>Звітний місяць<input type="month" data-month value="${h(month)}" required></label><button data-refresh>Оновити</button><button data-export>Повна копія</button></div><p class="space-source">Звіти РК і ВП додаємо вручну. Обери місяць, внеси зведений звіт і показники каналів, потім звір джерела. Порожнє поле означає «даних немає»; нуль — підтверджений нуль. Автоматичного отримання даних немає.</p><div class="space-grid"><article class="space-card"><h2>1. Зведений звіт</h2><button class="primary" data-month-new="reports">+ Звіт за ${h(month)}</button>${reports.map(r=>{const check=reportReadiness(r);return `<h3>${h(r.month)} · ${h(r.status)}</h3><p>${h(r.source||'Джерело не вказано')}</p><p>${check.ready?'Основні поля заповнені. Підтвердь звірку з джерелом.':'Потрібно звірити: '+h([...check.missing,...check.warnings].join(' · '))}</p><button data-record-module="reports" data-record-id="${h(r.id)}">Відкрити / звірити</button>`;}).join('')||'<p>Звіту за цей місяць ще немає.</p>'}</article><article class="space-card"><h2>2. Канали РК / джерела ВП</h2><button data-month-new="attribution">+ Канал за ${h(month)}</button><p>Каналів: ${channels.length} · перевірено: ${channels.filter(r=>r.quality==='Перевірено').length}</p>${channels.map(r=>`<button data-record-module="attribution" data-record-id="${h(r.id)}">${h(r.source)} · ${h(r.quality)}</button>`).join('')}<p>Указуй витрати й конверсії лише за однаковий період та метод підрахунку. Не дублюй одні й ті самі підключення між каналами.</p></article><article class="space-card"><h2>3. Завантажити CSV каналів</h2><button data-csv-template>Завантажити порожній шаблон</button><label>CSV за ${h(month)}<input type="file" data-channel-csv accept=".csv,text/csv"></label><p>Експортуй заповнену таблицю як CSV UTF-8. Перед збереженням покажемо нові записи й конфлікти; наявні значення залишаться.</p></article><article class="space-card"><h2>Очікувані звіти</h2>${requests.map(r=>`<p>${h(r.pack)} · ${h(r.owner)} · ${h(r.deadline)} · ${h(r.status)}</p>`).join('')||'<p>Відкритих запитів немає.</p>'}<button data-record-module="report_requests">Відкрити запити звітів</button></article></div><div id="monthly-import-preview" role="status"></div>`;
 }
 function downloadCsv(){const url=URL.createObjectURL(new Blob(['\uFEFF'+channelCsvTemplate],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`CMO-channels-${month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function previewChannels(file){const target=root.querySelector('#monthly-import-preview');try{if(file.size>1000000)throw Error('CSV завеликий');const imported=parseChannelCsv(await file.text(),month),d=doc('attribution'),current=d?.payload||[],names=new Map(current.filter(r=>r.month===month).map(r=>[r.source.normalize('NFKC').toLocaleLowerCase('uk'),r.id]));for(const r of imported)r.id=names.get(r.source.normalize('NFKC').toLocaleLowerCase('uk'))||r.id;const merged=mergeDocument('attribution',current,imported),revision=d?.revision||0;
   target.innerHTML=`<h2>Перевір CSV за ${h(month)}</h2><p>Нових каналів: ${merged.added} · однакових: ${merged.identical} · конфліктів: ${merged.conflicts}. Наявні записи не замінюються. Нові записи мають статус «Немає даних» до ручної перевірки.</p><div class="table-scroll"><table><thead><tr><th>Канал</th><th>Витрати</th><th>Заявки</th><th>Валідні</th><th>Підключення</th></tr></thead><tbody>${imported.map(r=>`<tr><td>${h(r.source)}</td>${['spend','leads','validLeads','connections'].map(k=>`<td>${r[k]===null?'—':h(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><button data-save-channels ${merged.added?'':'disabled'}>Додати ${merged.added} нових каналів</button>`;
   target.querySelector('[data-save-channels]').onclick=async e=>{e.target.disabled=true;try{await request({op:'save',key:'attribution',revision,payload:merged.payload});await refresh();notice('Канали додано. Звір дані й познач якість у кожному записі.');}catch(error){target.insertAdjacentHTML('beforeend',`<p class="space-error">${h(error.message)}. Імпорт не збережено; онови розділ і завантаж CSV ще раз.</p>`);}};
  }catch(error){target.textContent=error.message;}
 }
 async function go(next,id,prefill){if(fetching)return;key=next;part='lines';filter='';document.querySelector('#workspace').hidden=true;document.querySelector('#new-task').hidden=true;root.hidden=false;root.innerHTML='<p>Завантаження…</p>';document.querySelector('#heading').textContent=sections[key]||views[key]||'Експорт / імпорт';document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.space===key));const loaded=await refresh();if(!loaded)return;if(id){const index=rows().findIndex(r=>r.id===id);if(index>=0)edit(index);}else if(prefill)edit(null,prefill);}
 async function showBackupStatus(){const target=root.querySelector('#backup-status');if(!target)return;try{const result=await backupStatus();if(!target.isConnected)return;const b=result?.latest;target.textContent=b?`Остання копія: ${new Date(b.createdAt).toLocaleString('uk-UA',{timeZone:'Europe/Kyiv'})} · перевірка: ${b.verification?.status==='passed'?'пройшла':'не підтверджена'} · зберігаємо ${result.retention} копій.`:'Дані про серверні копії недоступні.';}catch(e){if(target.isConnected)target.textContent='Не вдалося перевірити копії: '+e.message;}}
 function renderTransfer(){root.innerHTML='<div class="space-toolbar"><button data-export class="primary">Завантажити повну копію</button></div><p class="space-source">Копія містить усі розділи CMO та доступні керівнику командні задачі. Імпорт додає нові записи; наявні записи з тим самим ідентифікатором зберігає. Задачі з нового повного експорту не імпортуються автоматично, щоб не створити дублікати.</p><label class="space-upload">Імпортувати експорт CMO<input type="file" data-import accept="application/json,.json"></label><div id="space-import-preview"></div><p class="space-source">Щоденні серверні копії: 30 останніх днів, із перевіркою відновлення в тимчасові таблиці. Копії поза сервером зберігаються щотижня окремим процесом у ChatGPT.</p><p id="backup-status" role="status">Перевіряємо останню копію…</p><h2>Стан відновлення</h2><div class="space-grid">'+documents.map(d=>`<article class="space-card"><h3>${h(sections[d.key]||d.key)}</h3><p>${d.source==='cmo-space-v29'?'Перенесено серверні дані':d.source==='rebuilt-empty'?'Перебудовано; локальні дані не відновлено':'Створено у Workspace'}</p><p>Версія ${d.revision} · записів ${rowsFor(d.key,d.payload).length}</p></article>`).join('')+'</div>';showBackupStatus();}
 async function previewImport(file){const target=root.querySelector('#space-import-preview');try{if(file.size>15000000)throw Error('Файл завеликий');const imported=parseImport(JSON.parse(await file.text())),plan=imported.map(({key:k,payload:p})=>{const d=doc(k),m=mergeDocument(k,d?.payload,p);return {key:k,revision:d?.revision||0,...m};});target.innerHTML='<h2>Перед імпортом</h2><p>Наявні записи залишаться. Конфлікти пропускаються; історія збережень ведеться для кожного зміненого розділу.</p><ul>'+plan.map(p=>`<li>${h(sections[p.key])}: нових ${p.added}, однакових ${p.identical}, конфліктів ${p.conflicts}</li>`).join('')+'</ul><button data-confirm-import>Додати нові записи</button>';target.querySelector('button').onclick=async e=>{e.target.disabled=true;try{await request({op:'import',documents:plan.filter(p=>JSON.stringify(p.payload)!==JSON.stringify(doc(p.key)?.payload)).map(({key,revision,payload})=>({key,revision,payload}))});await refresh();notice('Імпорт завершено. Наявні записи збережено.');}catch(e){notice(e.message+' Імпорт не застосовано. Онови дані та повтори.');}finally{e.target.disabled=false;}};}catch(e){target.textContent=e.message;}}
 nav.addEventListener('click',e=>{const b=e.target.closest('[data-space]');if(b&&actor?.role==='owner')go(b.dataset.space);});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-csv-template'))downloadCsv();if(b.hasAttribute('data-month-new'))go(b.dataset.monthNew,null,{month});if(b.hasAttribute('data-record-module'))go(b.dataset.recordModule,b.dataset.recordId);if(b.hasAttribute('data-open-task'))openTask(b.dataset.openTask);if(b.hasAttribute('data-assignee'))openAssignee(b.dataset.assignee);if(b.hasAttribute('data-refresh'))refresh();if(b.hasAttribute('data-edit'))edit(Number(b.dataset.edit));if(b.hasAttribute('data-add'))edit(null);if(b.hasAttribute('data-export'))exportAll();if(b.hasAttribute('data-history'))history();if(b.hasAttribute('data-envelope'))envelope();if(b.hasAttribute('data-part')){part=b.dataset.part;render();}});
 root.addEventListener('input',e=>{if(e.target.hasAttribute('data-search')){filter=e.target.value;const position=e.target.selectionStart;render();const input=root.querySelector('[data-search]');input.focus();input.setSelectionRange(position,position);}});
 root.addEventListener('change',e=>{if(e.target.hasAttribute('data-month')){if(validMonth(e.target.value)){month=e.target.value;render();}return;}if(e.target.hasAttribute('data-channel-csv')&&e.target.files[0])previewChannels(e.target.files[0]);if(e.target.hasAttribute('data-import')&&e.target.files[0])previewImport(e.target.files[0]);if(e.target.hasAttribute('data-report-select')){reportId=e.target.value;render();}});
 return {setActor(a){actor=a;nav.hidden=a?.role!=='owner';},hide(){root.hidden=true;}};
}
