import {escapeHtml as h} from './metrics.js';
import {modules,templates,extraLabels,choices,emptyPayload,rowsFor,replaceRows,recordTitle,safeLink,parseImport,mergeDocument,validatePayload,reportMetrics} from './space-model.js';
const sections=modules;
const labels={name:'Назва',title:'Назва',stage:'Етап',progress:'Прогрес, %',budget:'Бюджет',owner:'Відповідальний',due:'Дедлайн',tone:'Позначка',day:'День',status:'Статус',channel:'Канал',pillar:'Напрям',format:'Формат',objective:'Мета',hook:'Початок / хук',cta:'Заклик до дії',gates:'Готовність',brief:'Бриф',copy:'Текст',visual:'Візуал',approval:'Погодження',tracking:'Відстеження',context:'Контекст',requester:'Ініціатор',priority:'Пріоритет',impact:'Вплив',risk:'Ризик',recommendation:'Рекомендація',outcome:'Результат',related:'Пов’язане',month:'Місяць',spend:'Витрати',impressions:'Покази',clicks:'Кліки',users:'Користувачі',sessions:'Сесії',coverage:'Покриття',leads:'Ліди',validLeads:'Валідні ліди',connections:'Підключення',revenue:'Дохід',source:'Джерело',note:'Примітка',done:'Завершено'};
const defaults={campaigns:{name:'',stage:'План',progress:0,budget:'',owner:'',due:'',tone:''},content:{title:'',day:1,status:'План',owner:'',channel:'',pillar:'',format:'',objective:'',hook:'',cta:'',due:'',gates:{brief:false,copy:false,visual:false,approval:false,tracking:false}},decisions:{title:'',context:'',owner:'',status:'Потребує рішення',requester:'',due:'',priority:'Medium',impact:'',risk:'',recommendation:'',outcome:'',related:''},reports:{month:'',status:'Чернетка',spend:0,impressions:0,clicks:0,users:0,sessions:0,coverage:0,leads:0,validLeads:0,connections:0,revenue:0,source:'',note:''}};
Object.assign(labels,extraLabels);
Object.assign(defaults,templates);
export function applyEdits(original,entries){
 const record=structuredClone(original);
 for(const {key,value,type} of entries){
  if(key==='id')continue;
  if(type==='number'){if(value.trim()===''||!Number.isFinite(Number(value)))throw Error('Заповни числові поля');record[key]=Number(value);}
  else if(type==='boolean')record[key]=value===true;
  else if(type==='object')record[key]=JSON.parse(value);
  else record[key]=value;
 }
 return record;
}
const numberFields=new Set(['planned','actual','targetLeads','actualLeads','targetConnections','actualConnections','capacity','allocated','envelope','spend','visits','leads','validLeads','connections','revenue','promoCost','margin','retention','target']);
const statusChoices={insights:['Новий','Перевіряємо','Підтверджено','Відхилено'],roadmap:['Заплановано','У роботі','Заблоковано','Готово'],budget:['Чернетка','Погоджено','Активно','Стоп'],promos:['Потрібні дані','На оцінці','Погоджено','Завершити'],rhythm:['Заплановано','Сьогодні','Очікує','Готово'],experiments:['Backlog','Готовий','Запущено','Завершено'],execution:['До роботи','У роботі','Заблоковано','Готово'],automations:['Очікує налаштування','Очікує доступ','Заблоковано','Готово','Активно'],report_requests:['Очікуємо','Отримано','Перевірено']};
export function mountOwnerSpace({request,notice,getTasks=()=>[]}){
 const root=document.querySelector('#owner-space'),nav=document.querySelector('#owner-nav');
 let actor,key,documents=[],fetching=false,part='lines',filter='',reportId;
 const views={overview:'Огляд CMO',review:'Рев’ю керівника',strategy:'Стратегія',analytics:'Аналітика',funnel:'Воронка',sources:'Джерела даних'};
 const groups=[['Робота',['campaigns','launches','content','decisions','execution','legacy_tasks']],['Планування',['roadmap','budget','promos','rhythm','team_ops']],['Дослідження й дані',['insights','experiments','attribution','reports','report_requests']],['Інструменти',['visual','automations']]];
 nav.innerHTML='<small>ПРОСТІР КЕРІВНИКА</small>'+Object.entries(views).map(([k,label])=>`<button data-space="${k}">${h(label)}</button>`).join('')+groups.map(([label,keys])=>`<details ${label==='Робота'?'open':''}><summary>${label}</summary>${keys.map(k=>`<button data-space="${k}">${h(sections[k])}</button>`).join('')}</details>`).join('')+'<button data-space="transfer">Експорт / імпорт</button>';
 const dialog=document.createElement('dialog');dialog.innerHTML='<div class="dialog-head"><h2></h2><button type="button" data-close aria-label="Закрити">×</button></div><div class="space-dialog-body"></div><p class="space-error" role="status"></p>';document.body.append(dialog);
 const body=dialog.querySelector('.space-dialog-body'),error=dialog.querySelector('.space-error');
 dialog.querySelector('[data-close]').onclick=()=>dialog.close();
 function open(title){error.textContent='';dialog.querySelector('h2').textContent=title;if(!dialog.open)dialog.showModal();}
 function doc(k=key){return documents.find(d=>d.key===k);}
 function payload(){return doc()?.payload??emptyPayload(key);}
 function rows(){return rowsFor(key,payload(),part);}
 function valueMarkup(k,v){
  if(v===null||v===undefined||v==='')return '';
  if(typeof v==='boolean')return `<div class="space-value"><span>${h(labels[k]||k)}</span><p>${v?'Так':'Ні'}</p></div>`;
  if(typeof v==='object')return `<details class="space-nested"><summary>${h(labels[k]||k)}</summary>${Array.isArray(v)?v.map(r=>typeof r==='object'?`<article><strong>${h(recordTitle(r))}</strong>${Object.entries(r).filter(([a])=>!['id','title','name','src'].includes(a)).map(([a,b])=>valueMarkup(a,b)).join('')}${r.src&&safeLink(r.src)?`<a href="${h(safeLink(r.src))}" target="_blank" rel="noopener noreferrer">Відкрити зображення</a>`:''}</article>`:`<p>${h(r)}</p>`).join(''):Object.entries(v).map(([a,b])=>valueMarkup(a,b)).join('')}</details>`;
  const link=['url','src','linked'].includes(k)?safeLink(v):null;
  return `<div class="space-value"><span>${h(labels[k]||k)}</span><p>${link?`<a href="${h(link)}" target="_blank" rel="noopener noreferrer">${h(v)}</a>`:h(v)}</p></div>`;
 }
 function card(r,i){return `<article class="space-card"><h2>${h(recordTitle(r))}</h2><div class="metadata">${[r.owner,r.stage||r.status||r.approval,r.due||r.deadline].filter(Boolean).map(v=>`<span>${h(v)}</span>`).join('')}</div>${Object.entries(r).filter(([k])=>!['id','name','title','month','owner','stage','status','due','deadline','tone'].includes(k)).map(([k,v])=>valueMarkup(k,v)).join('')}<button data-edit="${i}">Відкрити / редагувати</button></article>`;}
 function render(){
  if(key==='transfer'){renderTransfer();return;}
  if(views[key]){renderSummary();return;}
  const d=doc(),items=rows();if(!Array.isArray(items))throw Error('Непідтримуваний формат розділу');
  const source=d?.source==='cmo-space-v29'?'Дані перенесено з CMO Space.':d?.source==='rebuilt-empty'?'Розділ перебудовано. Старі локальні записи не відновлено; нові записи зберігаються у спільній базі.':'Дані Workspace.';
  const notes={reports:'Збережено вихідні статуси та примітки. Неповні дані потребують перевірки.',legacy_tasks:'Старі записи для звірки; вони не додані до командного задачника.',automations:'Це реєстр налаштувань і підтверджених запусків. Записи тут самі не запускають нагадування чи інтеграції.',team_ops:'План завантаження. Редагування цих записів не змінює права доступу команди.',rhythm:'План зустрічей і результатів. Нагадування ще не налаштовано.'};
  root.innerHTML=`<div class="space-toolbar"><p>${items.length} записів · версія ${d?.revision||0}</p><button data-refresh>Оновити розділ</button><button data-history>Історія</button><button data-export>Повна копія</button>${key!=='legacy_tasks'?'<button class="primary" data-add>+ Додати</button>':''}</div><p class="space-source">${source} ${notes[key]||''}</p>${key==='budget'?`<div class="space-toolbar"><button data-part="lines">Статті бюджету</button><button data-part="resources">Ресурси</button><span>Ліміт: ${payload().envelope==null?'не задано':h(payload().envelope)+' грн'}</span><button data-envelope>Задати ліміт</button></div>`:''}<label class="space-search">Знайти запис<input data-search value="${h(filter)}" placeholder="Назва, відповідальний, статус…"></label><div class="space-grid">${items.map((r,i)=>({r,i})).filter(({r})=>JSON.stringify(r).toLocaleLowerCase('uk').includes(filter.toLocaleLowerCase('uk'))).map(({r,i})=>card(r,i)).join('')||'<p>Записів немає. Додай перший запис або імпортуй збережений експорт.</p>'}</div>`;
 }
 async function refresh(){if(fetching)return;fetching=true;try{const r=await request({op:'list'});documents=r.documents;render();notice();}catch(e){notice(e.message);root.innerHTML='<p>Не вдалося отримати дані.</p><button data-refresh>Спробувати ще раз</button>';}finally{fetching=false;}}
 function fieldsMarkup(value,path=[],editKey=key){return Object.entries(value).filter(([k])=>k!=='id').map(([k,v])=>{
  const next=[...path,k],attr=`data-path="${h(JSON.stringify(next))}"`,label=h(labels[k]||k);
  if(k!=='cards'&&Array.isArray(v)&&v.every(r=>typeof r==='string'))return `<label>${label}<textarea ${attr} data-type="strings" rows="3">${h(v.join('\n'))}</textarea><small>Один пункт на рядок</small></label>`;
  if(v&&typeof v==='object')return `<fieldset><legend>${label}</legend>${Array.isArray(v)?v.map((r,i)=>`<details open><summary>${h(recordTitle(r))}</summary>${fieldsMarkup(r,[...next,i],editKey)}</details>`).join(''):fieldsMarkup(v,next,editKey)}${k==='cards'?'<button type="button" data-add-note>+ Нотатка</button>':''}</fieldset>`;
  const type=typeof v==='boolean'?'boolean':typeof v==='number'||v===null&&numberFields.has(k)?'number':'string';
  if(type==='boolean')return `<label class="check"><input ${attr} data-type="boolean" type="checkbox" ${v?'checked':''}>${label}</label>`;
  if(type==='number')return `<label>${label}<input ${attr} data-type="number" data-nullable="${v===null}" type="number" step="any" value="${v===null?'':h(v)}" ${v===null?'':'required'}></label>`;
  const options=k==='status'?statusChoices[editKey]:choices[k];
  if(options)return `<label>${label}<select ${attr} data-type="string">${[...new Set([String(v??''),...options])].map(x=>`<option ${x===v?'selected':''}>${h(x)}</option>`).join('')}</select></label>`;
  return `<label>${label}<textarea ${attr} data-type="string" rows="2">${h(v??'')}</textarea></label>`;
 }).join('');}
 function readForm(form,original){const edited=structuredClone(original);for(const el of form.querySelectorAll('[data-path]')){const path=JSON.parse(el.dataset.path);if(path.some(k=>['__proto__','constructor','prototype'].includes(k)))throw Error('Неприпустиме поле');let holder=edited;for(const k of path.slice(0,-1))holder=holder[k];const k=path.at(-1);if(el.dataset.type==='number'){if(!el.value.trim()){if(el.dataset.nullable==='true')holder[k]=null;else throw Error('Заповни числові поля');}else{if(!Number.isFinite(Number(el.value)))throw Error('Перевір число');holder[k]=Number(el.value);}}else if(el.dataset.type==='boolean')holder[k]=el.checked;else if(el.dataset.type==='strings')holder[k]=el.value.split('\n').map(v=>v.trim()).filter(Boolean);else holder[k]=el.value;}return edited;}
 function edit(index){
  const editKey=key,editPart=part,d=doc(),revision=d?.revision||0,base=structuredClone(payload()),items=structuredClone(rows()),template=key==='budget'&&part==='resources'?'resources':key;
  let original=index===null?{id:crypto.randomUUID(),...structuredClone(defaults[template])}:items[index];
  body.innerHTML='<form class="space-editor"></form>';const form=body.querySelector('form');open(index===null?'Новий запис':'Редагування запису');
  function draw(){form.innerHTML=fieldsMarkup(original,[],editKey)+'<button>Зберегти</button>';}
  draw();form.addEventListener('click',e=>{if(e.target.closest('[data-add-note]')){try{original=readForm(form,original);original.cards.push({id:crypto.randomUUID(),...structuredClone(templates.cards)});draw();}catch(e){error.textContent=e.message;}}});
  form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button:not([type=button])');button.disabled=true;error.textContent='';try{
   const edited=readForm(form,original);if(!String(edited.title||edited.name||edited.month||edited.source||edited.pack||edited.role||'').trim())throw Error('Заповни назву запису');
   if(editKey==='visual')edited.updated=new Date().toISOString();
   if(index===null)items.push(edited);else items[index]=edited;
   const next=replaceRows(editKey,base,items,editPart);validatePayload(editKey,next);
   await request({op:'save',key:editKey,revision,payload:next});dialog.close();await refresh();notice('Збережено');
  }catch(e){error.textContent=e.message+' Введені зміни залишилися у формі.';}finally{button.disabled=false;}};
 }
 async function exportAll(){try{const packet=await request({op:'export'}),blob=new Blob([JSON.stringify(packet,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pavutyna-cmo-full-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Повну копію підготовлено: розділи та командні задачі.');}catch(e){notice(e.message);}}
 async function history(){open('Історія розділу');body.textContent='Завантаження…';try{const data=await request({op:'history',key});body.innerHTML=(data.events||[]).map(e=>`<details><summary>Версія ${h(e.revision)} · ${h(new Date(e.created_at).toLocaleString('uk-UA'))}</summary>${rowsFor(key,e.payload,part).map(r=>`<article><h3>${h(recordTitle(r))}</h3>${Object.entries(r).filter(([k])=>k!=='id').map(([k,v])=>valueMarkup(k,v)).join('')}</article>`).join('')}${key==='budget'?valueMarkup('envelope',e.payload.envelope):''}</details>`).join('')||'<p>Після першого збереження тут з’явиться історія. Початкову копію збережено окремо.</p>';}catch(e){error.textContent=e.message;}}
 function envelope(){const d=doc(),revision=d?.revision||0,base=structuredClone(payload());open('Ліміт бюджету');body.innerHTML=`<form><label>Ліміт, грн<input name="envelope" type="number" min="0" step="any" value="${base.envelope==null?'':h(base.envelope)}" required></label><button>Зберегти</button></form>`;body.querySelector('form').onsubmit=async e=>{e.preventDefault();try{base.envelope=Number(new FormData(e.target).get('envelope'));await request({op:'save',key:'budget',revision,payload:base});dialog.close();await refresh();}catch(e){error.textContent=e.message;}};}
 function renderSummary(){
  const list=k=>rowsFor(k,doc(k)?.payload??emptyPayload(k)),reports=list('reports'),decisions=list('decisions'),launches=list('launches'),tasks=getTasks();
  const blocks=(label,items)=>`<article class="space-card"><h2>${h(label)}</h2>${items.length?items.map(r=>`<div class="space-value"><strong>${h(recordTitle(r))}</strong><p>${h(r.owner||'')} · ${h(r.status||r.lane||r.approval||'')}</p></div>`).join(''):'<p>Записів немає</p>'}</article>`;
  const metric=(label,value)=>`<div class="stat"><strong>${value==null?'—':h(typeof value==='number'?new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(value):value)}</strong><span>${h(label)}</span></div>`;
  const toolbar='<div class="space-toolbar"><button data-refresh>Оновити</button><button data-export>Повна копія</button></div>';
  if(['overview','review'].includes(key)){root.innerHTML=toolbar+`<div class="stats">${metric('Відкриті задачі',tasks.filter(t=>t.lane!=='done').length)}${metric('На перевірці',tasks.filter(t=>t.lane==='review').length)}${metric('Заблоковані',tasks.filter(t=>t.lane==='blocked').length)}${metric('Перевірені звіти',reports.filter(r=>r.status==='Перевірено').length)}</div><div class="space-grid">${blocks('Потребують рішення',decisions.filter(r=>!['Погоджено','Вирішено','Закрито','Відхилено'].includes(r.status)))}${blocks('Перевірити результати',tasks.filter(t=>['review','blocked'].includes(t.lane)))}${blocks('Звіти для звірки',reports.filter(r=>r.status!=='Перевірено'))}${blocks('Запуски до погодження',launches.filter(r=>r.approval!=='Погоджено'))}</div>`;return;}
  if(key==='strategy'){const roadmap=list('roadmap');root.innerHTML=toolbar+'<p class="space-source">План дій за горизонтами та підтверджені інсайти. Оновлюй їх у розділах «План на 90 днів» та «Інсайти».</p><div class="space-grid">'+['0–30','31–60','61–90'].map(horizon=>blocks(horizon+' днів',roadmap.filter(r=>r.horizon===horizon))).join('')+blocks('Підтверджені інсайти',list('insights').filter(r=>r.status==='Підтверджено'))+'</div>';return;}
  if(key==='sources'){renderTransfer();root.querySelector('[data-import]')?.closest('label').remove();root.insertAdjacentHTML('afterbegin','<p class="space-source">Перенесено серверні записи CMO Space та 85 початкових задач Workflow. Для інших модулів створено нову структуру. Дані з браузера не підмінено прикладами зі старого коду.</p>');return;}
  const report=reports.find(r=>r.id===reportId)||reports[0],m=reportMetrics(report),format=v=>v==null?'—':new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(v);
  root.innerHTML=toolbar+`<label class="space-search">Місячний звіт<select data-report-select>${reports.map(r=>`<option value="${h(r.id)}" ${r.id===report?.id?'selected':''}>${h(r.month)} · ${h(r.status)}</option>`).join('')}</select></label><p class="space-source">${m?'Розрахунки за звітом зі статусом «Перевірено».':'Звіт не перевірено. Показники ефективності не розраховуються; нижче — вихідні значення для звірки.'}</p><div class="stats">${metric('CPL, грн',m?.cpl)}${metric('CPQL, грн',m?.cpql)}${metric('CAC, грн',m?.cac)}${metric('Лід → підключення, %',m?.leadToConnection)}</div><div class="space-grid"><article class="space-card"><h2>${h(report?.month||'Звітів немає')}</h2>${report?Object.entries(report).filter(([k])=>k!=='id').map(([k,v])=>valueMarkup(k,v)).join(''):''}</article><article class="space-card"><h2>${key==='funnel'?'Етапи воронки':'Аналітика каналів'}</h2>${key==='funnel'?(report?['clicks','leads','validLeads','connections'].map(k=>valueMarkup(k,report[k])).join(''):'<p>Додай звіт</p>'):list('attribution').map(r=>`<h3>${h(r.source)}</h3><p>${h(r.quality)}</p><p>CPL: ${r.quality==='Перевірено'&&r.leads>0&&typeof r.spend==='number'?h(format(r.spend/r.leads))+' грн':'—'}</p>${valueMarkup('note',r.note)}`).join('')||'<p>Додай дані у розділі «Атрибуція».</p>'}</article></div>`;
 }
 function renderTransfer(){root.innerHTML='<div class="space-toolbar"><button data-export class="primary">Завантажити повну копію</button></div><p class="space-source">Копія містить усі розділи CMO та доступні керівнику командні задачі. Імпорт додає нові записи; наявні записи з тим самим ідентифікатором зберігає. Задачі з нового повного експорту не імпортуються автоматично, щоб не створити дублікати.</p><label class="space-upload">Імпортувати експорт CMO<input type="file" data-import accept="application/json,.json"></label><div id="space-import-preview"></div><h2>Стан відновлення</h2><div class="space-grid">'+documents.map(d=>`<article class="space-card"><h3>${h(sections[d.key]||d.key)}</h3><p>${d.source==='cmo-space-v29'?'Перенесено серверні дані':d.source==='rebuilt-empty'?'Перебудовано; локальні дані не відновлено':'Створено у Workspace'}</p><p>Версія ${d.revision} · записів ${rowsFor(d.key,d.payload).length}</p></article>`).join('')+'</div>';}
 async function previewImport(file){const target=root.querySelector('#space-import-preview');try{if(file.size>15000000)throw Error('Файл завеликий');const imported=parseImport(JSON.parse(await file.text())),plan=imported.map(({key:k,payload:p})=>{const d=doc(k),m=mergeDocument(k,d?.payload,p);return {key:k,revision:d?.revision||0,...m};});target.innerHTML='<h2>Перед імпортом</h2><p>Наявні записи залишаться. Конфлікти пропускаються; історія збережень ведеться для кожного зміненого розділу.</p><ul>'+plan.map(p=>`<li>${h(sections[p.key])}: нових ${p.added}, однакових ${p.identical}, конфліктів ${p.conflicts}</li>`).join('')+'</ul><button data-confirm-import>Додати нові записи</button>';target.querySelector('button').onclick=async e=>{e.target.disabled=true;try{await request({op:'import',documents:plan.filter(p=>JSON.stringify(p.payload)!==JSON.stringify(doc(p.key)?.payload)).map(({key,revision,payload})=>({key,revision,payload}))});await refresh();notice('Імпорт завершено. Наявні записи збережено.');}catch(e){notice(e.message+' Імпорт не застосовано. Онови дані та повтори.');}finally{e.target.disabled=false;}};}catch(e){target.textContent=e.message;}}
 nav.addEventListener('click',e=>{const b=e.target.closest('[data-space]');if(!b||actor?.role!=='owner')return;key=b.dataset.space;part='lines';filter='';document.querySelector('#workspace').hidden=true;document.querySelector('#new-task').hidden=true;root.hidden=false;root.innerHTML='<p>Завантаження…</p>';document.querySelector('#heading').textContent=sections[key]||views[key]||'Експорт / імпорт';document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));refresh();});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-refresh'))refresh();if(b.hasAttribute('data-edit'))edit(Number(b.dataset.edit));if(b.hasAttribute('data-add'))edit(null);if(b.hasAttribute('data-export'))exportAll();if(b.hasAttribute('data-history'))history();if(b.hasAttribute('data-envelope'))envelope();if(b.hasAttribute('data-part')){part=b.dataset.part;render();}});
 root.addEventListener('input',e=>{if(e.target.hasAttribute('data-search')){filter=e.target.value;const position=e.target.selectionStart;render();const input=root.querySelector('[data-search]');input.focus();input.setSelectionRange(position,position);}});
 root.addEventListener('change',e=>{if(e.target.hasAttribute('data-import')&&e.target.files[0])previewImport(e.target.files[0]);if(e.target.hasAttribute('data-report-select')){reportId=e.target.value;render();}});
 return {setActor(a){actor=a;nav.hidden=a?.role!=='owner';},hide(){root.hidden=true;}};
}
