import {escapeHtml as h} from './metrics.js';
export const fileMimes={pdf:'application/pdf',txt:'text/plain',csv:'text/csv',json:'application/json',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',zip:'application/zip',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',mp4:'video/mp4',mp3:'audio/mpeg',wav:'audio/wav'};
export function validateFile(file){const mime=fileMimes[file.name.split('.').at(-1).toLowerCase()];if(!mime||file.size<1||file.size>20*1024*1024)throw Error('Підтримуються зображення, документи, ZIP, MP4 та аудіо до 20 МБ.');return mime;}
export function taskToolsMarkup(t,tasks,assignees,actor){const work=t.permissions?.work===true,edit=t.permissions?.edit===true,children=(t.childIds||[]).map(id=>tasks.find(t=>t.id===id)),files=(t.attachments||[]).filter(f=>f.status!=='removed');
 return `<div class="task-tools-grid"><section class="task-section"><h3>Чеклист · ${(t.checklist||[]).filter(c=>c.done).length}/${(t.checklist||[]).length}</h3>${(t.checklist||[]).map((c,i)=>`<div class="check-row"><label class="check"><input type="checkbox" data-check="${i}" ${c.done?'checked':''} ${work?'':'disabled'}>${h(c.text)}</label>${work?`<details><summary aria-label="Редагувати пункт">✎</summary><form data-tool="checklist_edit"><input type="hidden" name="index" value="${i}"><input name="text" aria-label="Текст пункту" maxlength="2000" value="${h(c.text)}" required><button>Зберегти</button></form><button data-tool="checklist_remove" data-index="${i}">Прибрати пункт</button></details>`:''}</div>`).join('')||'<p class="empty">Пунктів ще немає</p>'}${work?'<form data-tool="checklist_add" class="inline-form"><input name="text" placeholder="Новий пункт чеклиста" aria-label="Новий пункт чеклиста" maxlength="2000" required><button>+ Пункт</button></form>':''}</section>
 <section class="task-section"><h3>Підзадачі · ${children.filter(c=>c?.lane==='done').length}/${children.length}</h3>${t.parentId?`<button data-open-related="${h(t.parentId)}">↖ Батьківська задача</button>`:''}${children.map((c,i)=>c?`<button class="task-child" data-open-related="${h(c.id)}"><span>${h(c.title)}</span><small>${h(c.assignee)} · ${h(c.lane)}</small></button>`:`<p>Підзадача недоступна · ${h((t.childIds||[])[i])}</p>`).join('')}${work&&!t.parentId?`<details><summary>+ Підзадача</summary><form data-tool="subtask_create"><label>Назва<input name="title" maxlength="500" required></label><label>Результат<textarea name="description" rows="3" maxlength="20000"></textarea></label><label>Виконавець<select name="assignee">${(actor.role==='executor'?[actor.name]:assignees).map(n=>`<option ${n===t.assignee?'selected':''}>${h(n)}</option>`).join('')}</select></label><label>Дедлайн<input name="due" type="date"></label><button>Створити підзадачу</button></form><p>Це окрема задача з відповідальним, статусом і рев’ю. Батьківську здаємо після приймання підзадач.</p></details>`:''}</section>
 <section class="task-section"><h3>Файли · ${files.filter(f=>f.status==='ready').length}</h3>${files.map(f=>`<div class="task-file"><div><strong>${h(f.name)}</strong><small>${(f.size/1024/1024).toFixed(2)} МБ · ${f.status==='ready'?'Завантажено':'Завантаження не завершене'}</small></div>${f.status==='ready'?`<button data-file-download="${h(f.id)}">Завантажити</button>`:work?`<button data-tool="attachment_confirm" data-attachment-id="${h(f.id)}">Перевірити завантаження</button>`:''}${work?`<button data-tool="attachment_remove" data-attachment-id="${h(f.id)}" aria-label="Прибрати вкладення ${h(f.name)}">×</button>`:''}</div>`).join('')||'<p class="empty">Файлів ще немає</p>'}${work?'<label class="file-drop">+ Додати файл<input type="file" data-task-file accept=".pdf,.txt,.csv,.json,.doc,.docx,.xls,.xlsx,.zip,.png,.jpg,.jpeg,.webp,.gif,.mp4,.mp3,.wav"></label><p class="task-help">До 20 МБ на файл. Завантаження доступне лише учасникам цієї задачі.</p>':''}${actor.role==='owner'&&(t.attachments||[]).some(f=>f.status==='removed')?`<details><summary>Прибрані вкладення</summary>${t.attachments.filter(f=>f.status==='removed').map(f=>`<p>${h(f.name)} <button data-tool="attachment_restore" data-attachment-id="${h(f.id)}">Відновити</button></p>`).join('')}</details>`:''}</section>
 <section class="task-section"><h3>Зв’язки</h3>${(t.links||[]).map(l=>`<div class="task-link"><span>${h({related:'Пов’язано',blocks:'Блокує',duplicate:'Дублікат'}[l.relation]||l.relation)}</span><button data-open-related="${h(l.targetId)}">${h(tasks.find(t=>t.id===l.targetId)?.title||'Задача недоступна')}</button>${work?`<button data-tool="task_unlink" data-link-id="${h(l.id)}" aria-label="Прибрати зв’язок">×</button>`:''}</div>`).join('')||'<p class="empty">Зв’язків ще немає</p>'}${work?`<details><summary>+ Зв’язок</summary><form data-tool="task_link"><label>Тип<select name="relation"><option value="related">Пов’язано</option><option value="blocks">Блокує</option><option value="duplicate">Дублікат</option></select></label><label>Задача<select name="targetId" required><option value="">Обери задачу</option>${tasks.filter(x=>x.id!==t.id).map(x=>`<option value="${h(x.id)}">${h(x.title)}</option>`).join('')}</select></label><button>Додати зв’язок</button></form></details>`:''}</section></div>`;
}
export function mountTaskTools(root,{getTask,getTasks,mutate,openTask,upload,download,notice}){
 root.addEventListener('submit',e=>{const form=e.target.closest('form[data-tool]');if(!form)return;e.preventDefault();mutate({op:form.dataset.tool,...Object.fromEntries(new FormData(form))});});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-open-related')){if(getTasks().some(t=>t.id===b.dataset.openRelated))openTask(b.dataset.openRelated);else notice('Ця задача недоступна у твоєму рівні доступу');}if(b.hasAttribute('data-file-download'))download(getTask().attachments.find(f=>f.id===b.dataset.fileDownload));if(b.dataset.tool)mutate({op:b.dataset.tool,...(b.dataset.index?{index:Number(b.dataset.index)}:b.hasAttribute('data-index')?{index:0}:{}),attachmentId:b.dataset.attachmentId,linkId:b.dataset.linkId});});
 root.addEventListener('change',e=>{if(e.target.matches('[data-task-file]')&&e.target.files[0])upload(e.target.files[0]);});
}
