import {escapeHtml as h} from './metrics.js';
import {templates,applyTemplate,deleteElement,connect,safeLink,bounds} from './whiteboard-model.js';
import {moveCard} from './mechanics-model.js';
import {mountBoardSession,portalAt} from './board-session.js';
const histories=new Map(),positions=new Map();
export function mountWhiteboard(root,{board,save,notice,tasks=[],openTask,actor,team,action,refresh}){
 if(!board)return;const history=histories.get(board.id)||{past:[],future:[]};histories.set(board.id,history);let saving=false,drag=null;
 const z=Math.max(25,Math.min(200,board.zoom||100))/100;
 const remember=()=>({cards:structuredClone(board.cards||[]),edges:structuredClone(board.edges||[]),template:board.template});
 async function commit(next,record=true){if(saving)return false;saving=true;const pos={x:viewport.scrollLeft,y:viewport.scrollTop};positions.set(board.id,pos);const before=remember(),oldPast=history.past.slice(),oldFuture=history.future.slice();if(record){history.past.push(before);if(history.past.length>40)history.past.shift();history.future=[];}const ok=await save(next);if(ok===false&&record){history.past=oldPast;history.future=oldFuture;}saving=false;return ok!==false;}
 const tools=[['note','Нотатка'],['text','Текст'],['shape','Фігура'],['frame','Фрейм'],['link','Посилання'],['image','Зображення'],['task','Задача']];
 root.innerHTML=`<div class="wb-shell"><div class="wb-toolbar"><div>${tools.map(([kind,title])=>`<button data-wb-add="${kind}">${title}</button>`).join('')}<button data-wb-template>Шаблони</button></div><div><button data-wb-undo ${history.past.length?'':'disabled'} aria-label="Скасувати останню дію">↶</button><button data-wb-redo ${history.future.length?'':'disabled'} aria-label="Повторити дію">↷</button><button data-board-zoom="-10" aria-label="Зменшити масштаб">−</button><span>${Math.round(z*100)}%</span><button data-board-zoom="10" aria-label="Збільшити масштаб">+</button><button data-wb-fit>Вмістити</button><button data-wb-export>JSON</button><button data-wb-svg>SVG</button></div></div><p class="wb-hint">Перетягуй за заголовок · тягни фон для навігації · редагуй картку кнопкою ✎ · зв’язки додавай у картці</p><div class="board-scroll wb-viewport"><div class="wb-spacer"><div class="visual-canvas" data-board-id="${h(board.id)}"><svg class="wb-edges" width="4300" height="4300" aria-label="Зв’язки між картками"><defs><marker id="wb-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8"/></marker></defs></svg>${[...board.cards].sort((a,b)=>(a.kind==='frame'?0:1)-(b.kind==='frame'?0:1)).map(c=>`<article tabindex="0" class="visual-note wb-${h(['frame','text','shape','link','task','image'].includes(c.kind)?c.kind:'note')} note-${['blue','red','green','yellow','purple'].includes(c.color)?c.color:'blue'}" data-note="${h(c.id)}"><div class="wb-card-head"><h3 class="note-handle">${h(c.title||'Нотатка')}</h3><button data-wb-edit="${h(c.id)}" aria-label="Редагувати ${h(c.title||'картку')}">✎</button></div><p>${h(c.body||'')}</p>${c.kind==='task'?`<button data-wb-task="${h(c.taskId||'')}">${h(tasks.find(t=>t.id===c.taskId)?.title||'Задачу не знайдено')}</button>`:''}${c.url&&safeLink(c.url)?`<a href="${h(safeLink(c.url))}" target="_blank" rel="noopener noreferrer">Відкрити матеріал ↗</a>`:''}${c.kind==='image'&&safeLink(c.url)?`<img src="${h(safeLink(c.url))}" alt="${h(c.title)}" loading="lazy" referrerpolicy="no-referrer">`:''}<small>${h(c.tag||'')}</small><div class="note-controls">${[['←',-40,0],['↑',0,-40],['↓',0,40],['→',40,0]].map(([t,x,y])=>`<button data-note-move="${h(c.id)}" data-dx="${x}" data-dy="${y}" aria-label="Перемістити ${t}">${t}</button>`).join('')}</div><button class="wb-resize" data-wb-resize="${h(c.id)}" aria-label="Змінити розмір картки">◢</button></article>`).join('')}</div></div></div><div class="wb-dialog-host"></div></div>`;
 const viewport=root.querySelector('.wb-viewport'),canvas=root.querySelector('.visual-canvas'),spacer=root.querySelector('.wb-spacer');canvas.style.transform=`scale(${z})`;spacer.style.width=4300*z+'px';spacer.style.height=4300*z+'px';const pos=positions.get(board.id);if(pos){viewport.scrollLeft=pos.x;viewport.scrollTop=pos.y;}
 for(const c of board.cards){const el=[...canvas.querySelectorAll('[data-note]')].find(e=>e.dataset.note===c.id);el.style.left=Math.max(0,c.x||0)+'px';el.style.top=Math.max(0,c.y||0)+'px';el.style.width=(c.width||260)+'px';el.style.minHeight=(c.height||190)+'px';}
 function edges(){const svg=canvas.querySelector('svg');svg.querySelectorAll('line').forEach(e=>e.remove());for(const e of board.edges||[]){const a=board.cards.find(c=>c.id===e.from),b=board.cards.find(c=>c.id===e.to);if(!a||!b)continue;const line=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,v]of Object.entries({x1:(a.x||0)+(a.width||260)/2,y1:(a.y||0)+(a.height||190)/2,x2:(b.x||0)+(b.width||260)/2,y2:(b.y||0)+(b.height||190)/2,'marker-end':'url(#wb-arrow)'}))line.setAttribute(k,String(v));svg.append(line);}}edges();
 function dialog(content){const host=root.querySelector('.wb-dialog-host');host.innerHTML=`<dialog class="wb-editor"><button data-wb-close aria-label="Закрити">×</button>${content}<p class="space-error" role="status"></p></dialog>`;const d=host.querySelector('dialog');d.showModal();d.querySelector('[data-wb-close]').onclick=()=>d.close();return d;}
 function editor(card){const c=card||{id:crypto.randomUUID(),kind:'note',title:'',body:'',color:'yellow',x:Math.round(viewport.scrollLeft/z+80),y:Math.round(viewport.scrollTop/z+80),width:260,height:190};const d=dialog(`<h2>${card?'Редагувати картку':'Додати картку'}</h2><form><label>Назва<input name="title" value="${h(c.title)}" maxlength="500" required></label><label>Текст<textarea name="body" maxlength="20000" rows="5">${h(c.body||'')}</textarea></label><label>Тип<select name="kind">${tools.map(([v,t])=>`<option value="${v}" ${v===c.kind?'selected':''}>${t}</option>`).join('')}</select></label><label>Колір<select name="color">${[['yellow','Жовтий'],['blue','Синій'],['green','Зелений'],['red','Кораловий'],['purple','Фіолетовий']].map(([v,t])=>`<option value="${v}" ${v===c.color?'selected':''}>${t}</option>`).join('')}</select></label><label>Посилання на матеріал<input name="url" type="url" value="${h(c.url||'')}"></label><label>Пов’язана задача<select name="taskId"><option value="">Не обрано</option>${tasks.map(t=>`<option value="${h(t.id)}" ${t.id===c.taskId?'selected':''}>${h(t.title)}</option>`).join('')}</select></label><label>З’єднати з<select name="connectTo"><option value="">Без нового зв’язку</option>${board.cards.filter(x=>x.id!==c.id).map(x=>`<option value="${h(x.id)}">${h(x.title)}</option>`).join('')}</select></label><button>Зберегти</button>${card?'<button type="button" data-wb-delete>Видалити картку</button><button type="button" data-wb-clear-edges>Прибрати зв’язки картки</button>':''}</form>`);
 d.querySelector('form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));if(v.url&&!safeLink(v.url)){d.querySelector('.space-error').textContent='Використай HTTP або HTTPS посилання';return;}if(v.kind==='image'&&!safeLink(v.url)){d.querySelector('.space-error').textContent='Додай посилання на зображення';return;}if(v.kind==='task'&&!v.taskId){d.querySelector('.space-error').textContent='Обери пов’язану задачу';return;}const next={...c,...v};delete next.connectTo;let updated={...board,cards:card?board.cards.map(x=>x.id===c.id?next:x):[...board.cards,next]};if(v.connectTo)updated=connect(updated,c.id,v.connectTo);await commit(updated);};
 if(card){d.querySelector('[data-wb-delete]').onclick=()=>commit(deleteElement(board,c.id));d.querySelector('[data-wb-clear-edges]').onclick=()=>commit({...board,edges:(board.edges||[]).filter(e=>e.from!==c.id&&e.to!==c.id)});}}
 root.onclick=async e=>{const b=e.target.closest('button');if(!b||saving)return;if(b.dataset.wbAdd){editor({id:crypto.randomUUID(),kind:b.dataset.wbAdd,title:'Нова '+b.textContent.toLowerCase(),body:'',color:'yellow',x:Math.round(viewport.scrollLeft/z+80),y:Math.round(viewport.scrollTop/z+80),width:b.dataset.wbAdd==='frame'?620:260,height:b.dataset.wbAdd==='frame'?460:190});const d=root.querySelector('dialog');d.querySelector('[data-wb-delete]')?.remove();d.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const v=Object.fromEntries(new FormData(ev.target));if(v.url&&!safeLink(v.url)||v.kind==='task'&&!v.taskId||v.kind==='image'&&!safeLink(v.url)){d.querySelector('.space-error').textContent='Перевір посилання / обери задачу';return;}let n={...board,cards:[...board.cards,{id:crypto.randomUUID(),...v,x:Math.round(viewport.scrollLeft/z+80),y:Math.round(viewport.scrollTop/z+80),width:v.kind==='frame'?620:260,height:v.kind==='frame'?460:190}]};const added=n.cards.at(-1);if(v.connectTo)n=connect(n,added.id,v.connectTo);await commit(n);};}
 if(b.dataset.wbEdit)editor(board.cards.find(c=>c.id===b.dataset.wbEdit));if(b.hasAttribute('data-wb-task')&&tasks.some(t=>t.id===b.dataset.wbTask))openTask?.(b.dataset.wbTask);
 if(b.hasAttribute('data-wb-template')){const d=dialog(`<h2>Шаблони</h2><p>Шаблон додає фрейми й нотатки, зберігаючи наявні картки.</p><div class="wb-template-grid">${Object.entries(templates).map(([k,v])=>`<button data-template="${k}">${v}</button>`).join('')}</div>`);d.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>commit(applyTemplate(board,b.dataset.template)));}
 if(b.hasAttribute('data-board-zoom'))await commit({...board,zoom:Math.max(25,Math.min(200,(board.zoom||100)+Number(b.dataset.boardZoom)))},false);
 if(b.hasAttribute('data-note-move')){const c=board.cards.find(c=>c.id===b.dataset.noteMove);await commit(moveCard(board,c.id,(c.x||0)+Number(b.dataset.dx),(c.y||0)+Number(b.dataset.dy)));}
 if(b.hasAttribute('data-wb-fit')){const size=bounds(board.cards);positions.set(board.id,{x:0,y:0});viewport.scrollLeft=viewport.scrollTop=0;await commit({...board,zoom:Math.max(25,Math.min(100,Math.floor(Math.min((viewport.clientWidth||1000)/size.width,(viewport.clientHeight||600)/size.height)*100)))},false);}
 for(const [attr,from,to]of [['data-wb-undo',history.past,history.future],['data-wb-redo',history.future,history.past]])if(b.hasAttribute(attr)&&from.length){const snap=from.at(-1),current=remember();from.pop();to.push(current);if(!await commit({...board,...snap},false)){to.pop();from.push(snap);}}
 if(b.hasAttribute('data-wb-export'))download(JSON.stringify(board,null,2),'application/json','board.json');
 if(b.hasAttribute('data-wb-svg')){const size=bounds(board.cards);download(`<svg xmlns="http://www.w3.org/2000/svg" width="${Number(size.width)||4300}" height="${Number(size.height)||4300}" viewBox="0 0 ${size.width} ${size.height}"><rect width="100%" height="100%" fill="#10203b"/>${board.cards.map(c=>`<rect x="${Number(c.x)||0}" y="${Number(c.y)||0}" width="${Number(c.width)||260}" height="${Number(c.height)||190}" rx="12" fill="${c.kind==='frame'?'#20395b':'#f6d76d'}" stroke="#7186aa"/><text x="${(Number(c.x)||0)+15}" y="${(Number(c.y)||0)+32}" fill="${c.kind==='frame'?'#ffffff':'#172640'}" font-size="18">${h(c.title||'')}</text><text x="${(Number(c.x)||0)+15}" y="${(Number(c.y)||0)+60}" fill="#172640" font-size="13">${h((c.body||'').slice(0,100))}</text>`).join('')}</svg>`,'image/svg+xml','board.svg');}}
 function download(data,type,name){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 viewport.addEventListener('pointerdown',e=>{if(saving||e.target.closest('button,a,input,textarea'))return;const el=e.target.closest('[data-note]');if(el&&!e.target.closest('.note-handle'))return;const c=el?board.cards.find(c=>c.id===el.dataset.note):null;drag={c,el,startX:e.clientX,startY:e.clientY,x:c?.x||0,y:c?.y||0,left:viewport.scrollLeft,top:viewport.scrollTop};(e.target.closest('.note-handle')||viewport).setPointerCapture?.(e.pointerId);e.preventDefault();});
 viewport.addEventListener('pointermove',e=>{if(!drag)return;if(!drag.c){viewport.scrollLeft=drag.left-(e.clientX-drag.startX);viewport.scrollTop=drag.top-(e.clientY-drag.startY);return;}drag.x=Math.max(0,Math.min(4000,(drag.c.x||0)+(e.clientX-drag.startX)/z));drag.y=Math.max(0,Math.min(4000,(drag.c.y||0)+(e.clientY-drag.startY)/z));drag.el.style.left=drag.x+'px';drag.el.style.top=drag.y+'px';});
 viewport.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;const destination=d.c?.kind==='task'&&portalAt(root,e);if(destination){d.el.style.left=(d.c.x||0)+'px';d.el.style.top=(d.c.y||0)+'px';root.dispatchEvent(new CustomEvent('wb-portal',{detail:{taskId:d.c.taskId,destination}}));return;}if(d.c&&((d.c.x||0)!==d.x||(d.c.y||0)!==d.y))commit(moveCard(board,d.c.id,d.x,d.y));});viewport.addEventListener('pointercancel',()=>{if(drag?.c){drag.el.style.left=(drag.c.x||0)+'px';drag.el.style.top=(drag.c.y||0)+'px';}drag=null;});
 viewport.querySelectorAll('[data-wb-resize]').forEach(handle=>{let r;handle.onpointerdown=e=>{if(saving)return;e.stopPropagation();const c=board.cards.find(c=>c.id===handle.dataset.wbResize);r={c,startX:e.clientX,startY:e.clientY,w:c.width||260,h:c.height||190};handle.setPointerCapture?.(e.pointerId);};handle.onpointermove=e=>{if(!r)return;e.stopPropagation();r.w=Math.max(160,Math.min(1800,(r.c.width||260)+(e.clientX-r.startX)/z));r.h=Math.max(120,Math.min(1800,(r.c.height||190)+(e.clientY-r.startY)/z));handle.closest('[data-note]').style.width=r.w+'px';handle.closest('[data-note]').style.minHeight=r.h+'px';};handle.onpointerup=e=>{if(!r)return;e.stopPropagation();const v=r;r=null;commit({...board,cards:board.cards.map(c=>c.id===v.c.id?{...c,width:Math.round(v.w),height:Math.round(v.h)}:c)});};handle.onpointercancel=()=>{r=null;};});
 mountBoardSession(root,{board,tasks,actor,team,action,refresh,openTask});
}
